// web/src/ui/workouts/EditWorkout.vue
<script setup lang="ts">
import { timestampFromDate, type Timestamp } from '@bufbuild/protobuf/wkt'
import type { Workout } from '@/proto/api/v1/workout_service_pb'
import type { ExerciseSets, Set } from '@/proto/api/v1/shared_pb'

import { DateTime } from 'luxon'
import { computed, onMounted, ref } from 'vue'
import { useRoute } from 'vue-router'
import router from '@/router/router'
import { useAuthStore } from '@/stores/auth.ts'
import { useAlertStore } from '@/stores/alerts.ts'
import AppList from '@/ui/components/AppList.vue'
import { usePageTitleStore } from '@/stores/pageTitle'
import AppButton from '@/ui/components/AppButton.vue'
import AppListItem from '@/ui/components/AppListItem.vue'
import { ChevronDownIcon, ChevronUpIcon, MinusCircleIcon } from '@heroicons/vue/24/outline'
import { getWorkout, updateWorkout } from '@/http/requests.ts'
import AppListItemInput from '@/ui/components/AppListItemInput.vue'
import ExerciseTags from '@/ui/exercises/ExerciseTags.vue'
import DurationInput from '@/ui/workouts/DurationInput.vue'
import {
  hasAnyExerciseSetValue,
  isExerciseSetComplete,
  measurementsForExercise,
} from '@/utils/exerciseMeasurements'
import { normalizeWeightUnit, weightUnitLabel } from '@/utils/weightUnits'

const route = useRoute()
const workout = ref<Workout>()
const alertStore = useAlertStore()
const authStore = useAuthStore()
const pageTitleStore = usePageTitleStore()

onMounted(async () => {
  await fetchWorkout(route.params.id as string)
  pageTitleStore.setPageTitle(workout.value?.name as string)
})

const fetchWorkout = async (id: string) => {
  const res = await getWorkout(id)
  if (!res) return

  if (res.workout?.user?.id !== authStore.userId) {
    alertStore.setError('You do not have permission to edit this workout')
    await router.push('/home')
    return
  }

  workout.value = res.workout
}

const onUpdateWorkout = async () => {
  if (!workout.value) {
    return
  }

  workout.value.exerciseSets = workout.value.exerciseSets
    .map((exerciseSet) => {
      const sets = exerciseSet.sets.filter((set) =>
        isExerciseSetComplete(set, exerciseSet.exercise),
      )
      if (!sets.length) return null
      exerciseSet.sets = sets
      return exerciseSet
    })
    .filter(Boolean) as ExerciseSets[]

  const res = await updateWorkout(workout.value)
  if (!res) return

  alertStore.setSuccess('Workout updated')
  await router.push(`/workouts/${workout.value.id}`)
}

const addEmptySet = (exerciseId: string) => {
  if (!workout?.value) {
    return
  }

  workout.value.exerciseSets
    .find((es: ExerciseSets) => es.exercise?.id === exerciseId)
    ?.sets.push({
      $typeName: 'api.v1.Set',
      weightUnit: normalizeWeightUnit(workout.value.user?.weightUnit),
    } as Set)
}

const deleteSet = (exerciseId: string, index: number) => {
  if (!workout?.value) {
    return
  }

  workout.value.exerciseSets
    .find((es: ExerciseSets) => es.exercise?.id === exerciseId)
    ?.sets.splice(index, 1)
}

const setStartDateTime = (value: string) => {
  workout.value = {
    ...workout.value,
    startedAt: timestampFromDate(DateTime.fromISO(value).toJSDate()),
  } as Workout
}

const setEndDateTime = (value: string) => {
  workout.value = {
    ...workout.value,
    finishedAt: timestampFromDate(DateTime.fromISO(value).toJSDate()),
  } as Workout
}

const toDateTime = (timestamp: Timestamp | undefined) => {
  if (!timestamp) {
    return DateTime.now().toFormat("yyyy-MM-dd'T'HH:mm")
  }

  return DateTime.fromSeconds(Number(timestamp.seconds)).toFormat("yyyy-MM-dd'T'HH:mm")
}

const maxExerciseIndex = computed(() => {
  if (!workout.value?.exerciseSets) return 0
  return workout.value.exerciseSets.length - 1
})

const moveExercise = (index: number, direction: 'up' | 'down') => {
  const exercises = workout.value?.exerciseSets
  if (!exercises) return

  const newIndex = direction === 'up' ? index - 1 : index + 1
  if (newIndex < 0 || newIndex >= exercises.length) return
  ;[exercises[index], exercises[newIndex]] = [exercises[newIndex], exercises[index]]
}
</script>

<template>
  <form class="edit-workout-form" @submit.prevent="onUpdateWorkout">
    <template v-for="(es, index) in workout?.exerciseSets" :key="es.exercise?.id">
      <div class="flex justify-between pr-4">
        <div>
          <h6>{{ es.exercise?.name }}</h6>
          <ExerciseTags compact :tags="es.exercise?.tags" />
        </div>
        <div class="flex gap-x-1">
          <ChevronUpIcon
            v-if="index > 0"
            class="size-5 text-gray-500 cursor-pointer"
            @click="moveExercise(index, 'up')"
          />
          <ChevronDownIcon
            v-if="index < maxExerciseIndex"
            class="size-5 text-gray-500 cursor-pointer"
            @click="moveExercise(index, 'down')"
          />
        </div>
      </div>

      <AppList>
        <AppListItem class="flex flex-col">
          <div v-for="(set, index) in es.sets" :key="index" class="w-full">
            <label>Set {{ index + 1 }}</label>
            <div
              class="measurement-row"
              :style="{ '--metric-count': measurementsForExercise(es.exercise).length }"
            >
              <div
                v-for="measurement in measurementsForExercise(es.exercise)"
                :key="measurement.field"
                class="measurement-input"
              >
                <span>{{ measurement.label }}</span>
                <DurationInput
                  v-if="measurement.field === 'durationSeconds'"
                  v-model="set.durationSeconds"
                  :required="hasAnyExerciseSetValue(set, es.exercise)"
                />
                <div v-else-if="measurement.field === 'weight'" class="flex items-center gap-2">
                  <input
                    v-model.number="set.weight"
                    type="number"
                    inputmode="decimal"
                    min="0"
                    step="any"
                    :placeholder="measurement.label"
                    :required="hasAnyExerciseSetValue(set, es.exercise)"
                  />
                  <span class="weight-unit-suffix">{{ weightUnitLabel(set.weightUnit) }}</span>
                </div>
                <input
                  v-else
                  v-model.number="set[measurement.field]"
                  type="number"
                  :inputmode="measurement.inputmode"
                  min="0"
                  :step="measurement.field === 'reps' ? 1 : 'any'"
                  :placeholder="measurement.label"
                  :required="hasAnyExerciseSetValue(set, es.exercise)"
                />
              </div>
              <MinusCircleIcon
                class="remove-set"
                @click="deleteSet(es.exercise?.id as string, index)"
              />
            </div>
          </div>
          <AppButton
            colour="primary"
            type="button"
            class="w-full"
            @click="addEmptySet(es.exercise?.id as string)"
          >
            Add Set
          </AppButton>
        </AppListItem>
      </AppList>
    </template>

    <h6>Start Time</h6>
    <AppList>
      <AppListItemInput
        :model="toDateTime(workout?.startedAt)"
        type="datetime-local"
        required
        @update="setStartDateTime"
      />
    </AppList>

    <h6>End Time</h6>
    <AppList>
      <AppListItemInput
        :model="toDateTime(workout?.finishedAt)"
        type="datetime-local"
        required
        @update="setEndDateTime"
      />
    </AppList>

    <h6>Note</h6>
    <textarea
      v-if="workout"
      ref="textarea"
      v-model="workout.note"
      class="w-full border-gray-200 rounded-md focus:ring-indigo-500 focus:border-indigo-500 text-base min-h-20 py-3 mb-4 resize-none overflow-hidden"
      placeholder="How was it?"
    />

    <footer class="update-dock">
      <AppButton type="submit" colour="primary">Update Workout</AppButton>
      <AppButton type="link" :to="`/workouts/${workout?.id}`" colour="gray">
        Cancel Update
      </AppButton>
    </footer>
  </form>
</template>

<style scoped>
@reference '../../assets/base.css';

.edit-workout-form {
  @apply pb-32;
}

.update-dock {
  bottom: calc(4.5rem + env(safe-area-inset-bottom));
  @apply fixed inset-x-0 z-40 mx-auto flex max-w-3xl flex-col items-stretch gap-2 border-t border-slate-200 bg-white px-4 py-3 shadow-[0_-8px_24px_rgba(15,23,42,0.08)] sm:rounded-2xl sm:border;
}

label {
  @apply block text-sm font-semibold text-gray-600 uppercase mb-2;
}

input {
  @apply block w-full rounded-md border-0 bg-white px-3 py-3 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 font-medium;
}

.measurement-row {
  grid-template-columns: repeat(var(--metric-count), minmax(0, 1fr)) auto;
  @apply mb-4 grid items-end gap-3;
}

.measurement-input > span {
  @apply mb-1 block text-xs font-semibold text-slate-500;
}

.remove-set {
  @apply mb-3 size-7 cursor-pointer text-slate-500;
}

.weight-unit-suffix {
  @apply shrink-0 text-xs font-bold uppercase text-slate-400;
}

@media (max-width: 520px) {
  .measurement-row {
    @apply gap-2;
  }
}
</style>

// web/src/ui/workouts/EditWorkout.tsx
import type { Workout } from '@/proto/api/v1/workout_service_pb'
import type { SetChanges } from '@/ui/workouts/SetMeasurementInputs'
import { AppIconButton } from '@/ui/components/AppIconButton'
import { AppTextarea } from '@/ui/components/AppTextarea'
import type { Timestamp } from '@bufbuild/protobuf/wkt'

import { create } from '@bufbuild/protobuf'
import { timestampFromDate } from '@bufbuild/protobuf/wkt'
import { ChevronDownIcon, ChevronUpIcon } from '@heroicons/react/24/outline'
import { DateTime } from 'luxon'
import { useEffect, useState } from 'react'
import { useTranslation } from 'react-i18next'
import { useNavigate, useParams } from 'react-router-dom'

import { getWorkout, updateWorkout } from '@/http/requests'
import { SetSchema } from '@/proto/api/v1/shared_pb'
import { useToastStore } from '@/stores/toasts'
import { useAuthStore } from '@/stores/auth'
import { usePageTitleStore } from '@/stores/pageTitle'
import { AppButton } from '@/ui/components/AppButton'
import { AppList } from '@/ui/components/AppList'
import { AppListItem } from '@/ui/components/AppListItem'
import { AppListItemInput } from '@/ui/components/AppListItemInput'
import { AppOptionalAction } from '@/ui/components/AppOptionalAction'
import { AppSkeleton } from '@/ui/components/AppSkeleton'
import { ExerciseTags } from '@/ui/exercises/ExerciseTags'
import { SetMeasurementInputs } from '@/ui/workouts/SetMeasurementInputs'
import { normalizeDistanceUnit } from '@/utils/distanceUnits'
import { isExerciseSetComplete } from '@/utils/exerciseMeasurements'
import { normalizeWeightUnit } from '@/utils/weightUnits'
import styles from './EditWorkout.module.css'

const localInput = "yyyy-MM-dd'T'HH:mm"

const toLocalInput = (timestamp: Timestamp | undefined) =>
  timestamp
    ? DateTime.fromSeconds(Number(timestamp.seconds)).toFormat(localInput)
    : DateTime.now().toFormat(localInput)

/** Corrects a finished workout: its sets, when it ran, and the note on it. */
export const EditWorkout = () => {
  const { t } = useTranslation()
  const navigate = useNavigate()
  const { id = '' } = useParams()

  const [workout, setWorkout] = useState<Workout>()

  useEffect(() => {
    const load = async () => {
      const res = await getWorkout(id)
      if (!res) return

      // Editing someone else's workout is refused here as well as by the API,
      // so the form is never shown for one.
      if (res.workout?.user?.id !== useAuthStore.getState().userId) {
        useToastStore.getState().error(t('workout.edit.noPermission'))
        await navigate('/home')
        return
      }

      setWorkout(res.workout)
      usePageTitleStore.getState().setPageTitle(res.workout.name)
    }
    void load()
  }, [id, t, navigate])

  const onSubmit = async () => {
    if (!workout) return

    // A set left half-filled is dropped rather than saved as a real one, and an
    // exercise with nothing left in it goes with them.
    const exerciseSets = workout.exerciseSets
      .map((exerciseSet) => ({
        ...exerciseSet,
        sets: exerciseSet.sets.filter((set) => isExerciseSetComplete(set, exerciseSet.exercise)),
      }))
      .filter((exerciseSet) => exerciseSet.sets.length > 0)

    const res = await updateWorkout({ ...workout, exerciseSets })
    if (!res) return

    useToastStore.getState().success(t('workout.edit.updated'))
    await navigate(`/workouts/${workout.id}`)
  }

  const updateSets = (
    exerciseIndex: number,
    change: (
      sets: Workout['exerciseSets'][number]['sets'],
    ) => Workout['exerciseSets'][number]['sets'],
  ) =>
    setWorkout((current) => {
      if (!current) return current

      const exerciseSets = current.exerciseSets.map((exerciseSet, index) =>
        index === exerciseIndex ? { ...exerciseSet, sets: change(exerciseSet.sets) } : exerciseSet,
      )
      return { ...current, exerciseSets }
    })

  const moveExercise = (index: number, direction: -1 | 1) =>
    setWorkout((current) => {
      if (!current) return current

      const target = index + direction
      if (target < 0 || target >= current.exerciseSets.length) return current

      const exerciseSets = [...current.exerciseSets]
      const [moved] = exerciseSets.splice(index, 1)
      if (moved) exerciseSets.splice(target, 0, moved)
      return { ...current, exerciseSets }
    })

  if (!workout) return <AppSkeleton />

  return (
    <form
      className={styles.editWorkoutForm}
      onSubmit={(event) => {
        event.preventDefault()
        void onSubmit()
      }}
    >
      {workout.exerciseSets.map((exerciseSet, exerciseIndex) => (
        <div key={exerciseSet.exercise?.id}>
          <div className={styles.exerciseHeading}>
            <div>
              <h6>{exerciseSet.exercise?.name}</h6>
              <ExerciseTags compact tags={exerciseSet.exercise?.tags} />
            </div>
            <div className={styles.moveActions}>
              {exerciseIndex > 0 && (
                <AppIconButton
                  icon={ChevronUpIcon}
                  label={t('training.planForm.moveUp', { name: exerciseSet.exercise?.name })}
                  onClick={() => moveExercise(exerciseIndex, -1)}
                />
              )}
              {exerciseIndex < workout.exerciseSets.length - 1 && (
                <AppIconButton
                  icon={ChevronDownIcon}
                  label={t('training.planForm.moveDown', { name: exerciseSet.exercise?.name })}
                  onClick={() => moveExercise(exerciseIndex, 1)}
                />
              )}
            </div>
          </div>

          <AppList>
            <AppListItem className="flex flex-col">
              {exerciseSet.sets.map((set, setIndex) => (
                <div key={setIndex} className="w-full">
                  <label className={styles.setLabel}>
                    {t('common.set')} {setIndex + 1}
                  </label>
                  <SetMeasurementInputs
                    set={set}
                    exercise={exerciseSet.exercise}
                    removeLabel={t('workout.removeSet', { number: setIndex + 1 })}
                    onChange={(changes: SetChanges) =>
                      updateSets(exerciseIndex, (sets) =>
                        sets.map((candidate, index) =>
                          index === setIndex ? { ...candidate, ...changes } : candidate,
                        ),
                      )
                    }
                    onRemove={() =>
                      updateSets(exerciseIndex, (sets) =>
                        sets.filter((_, index) => index !== setIndex),
                      )
                    }
                  />
                </div>
              ))}

              <AppOptionalAction
                label={t('workout.edit.addSet')}
                onClick={() =>
                  updateSets(exerciseIndex, (sets) => [
                    ...sets,
                    create(SetSchema, {
                      weightUnit: normalizeWeightUnit(workout.user?.weightUnit),
                      distanceUnit: normalizeDistanceUnit(workout.user?.distanceUnit),
                    }),
                  ])
                }
              />
            </AppListItem>
          </AppList>
        </div>
      ))}

      <h6>{t('workout.edit.startTime')}</h6>
      <AppList>
        <AppListItemInput
          label={t('workout.edit.startTime')}
          model={toLocalInput(workout.startedAt)}
          type="datetime-local"
          required
          onUpdate={(value) =>
            setWorkout((current) =>
              current
                ? { ...current, startedAt: timestampFromDate(DateTime.fromISO(value).toJSDate()) }
                : current,
            )
          }
        />
      </AppList>

      <h6>{t('workout.edit.endTime')}</h6>
      <AppList>
        <AppListItemInput
          label={t('workout.edit.endTime')}
          model={toLocalInput(workout.finishedAt)}
          type="datetime-local"
          required
          onUpdate={(value) =>
            setWorkout((current) =>
              current
                ? { ...current, finishedAt: timestampFromDate(DateTime.fromISO(value).toJSDate()) }
                : current,
            )
          }
        />
      </AppList>

      <h6>{t('workout.edit.note')}</h6>
      <AppTextarea
        autosize
        className={styles.note}
        placeholder={t('workout.notePlaceholder')}
        rows={3}
        value={workout.note}
        onChange={(event) =>
          setWorkout((current) => (current ? { ...current, note: event.target.value } : current))
        }
      />

      <footer className={styles.updateDock}>
        <AppButton type="submit" colour="primary">
          {t('workout.edit.submit')}
        </AppButton>
        <AppButton type="link" to={`/workouts/${workout.id}`} colour="secondary">
          {t('common.cancel')}
        </AppButton>
      </footer>
    </form>
  )
}
