// web/src/ui/workouts/ViewWorkout.tsx
import type { Workout } from '@/proto/api/v1/workout_service_pb'

import { useEffect, useState } from 'react'
import { useTranslation } from 'react-i18next'
import { Link, useParams } from 'react-router-dom'

import { getWorkout } from '@/http/requests'
import { usePageTitleStore } from '@/stores/pageTitle'
import { AppSkeleton } from '@/ui/components/AppSkeleton'
import { CardWorkout } from '@/ui/components/CardWorkout'
import styles from './ViewWorkout.module.css'

/** One finished workout, in full. */
export const ViewWorkout = () => {
  const { t } = useTranslation()
  const { id = '' } = useParams()

  const [workout, setWorkout] = useState<Workout>()
  const [loading, setLoading] = useState(true)

  useEffect(() => {
    const load = async () => {
      const res = await getWorkout(id)
      setWorkout(res?.workout)
      usePageTitleStore.getState().setPageTitle(res?.workout?.name ?? t('common.workout'))
      setLoading(false)
    }
    void load()
  }, [id, t])

  if (loading) return <AppSkeleton />

  if (!workout) {
    return (
      <section className={styles.emptyCard}>
        <h1>{t('workout.view.unavailable')}</h1>
        <p>{t('workout.view.unavailableBody')}</p>
        <Link to="/workout">{t('workout.view.viewWorkouts')}</Link>
      </section>
    )
  }

  return <CardWorkout workout={workout} compact={false} />
}

// web/src/ui/workouts/ViewWorkout.vue
<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { useRoute } from 'vue-router'
import { usePageTitleStore } from '@/stores/pageTitle'
import CardWorkout from '@/ui/components/CardWorkout.vue'
import {
  type Workout,
} from '@/proto/api/v1/workout_service_pb.ts'
import {getWorkout} from "@/http/requests.ts";

const route = useRoute()
const workout = ref<Workout>()
const pageTitleStore = usePageTitleStore()

onMounted(async () => {
  await fetchWorkout()
  pageTitleStore.setPageTitle(workout?.value?.name as string)
})

const fetchWorkout = async () => {
  const res = await getWorkout(route.params.id as string)
  if (!res) return

  workout.value = res.workout
}
</script>

<template>
  <CardWorkout
    v-if="workout"
    :workout="workout"
    :compact="false"
  />
</template>

<style scoped></style>
