// web/src/ui/workouts/WorkoutView.vue
<script setup lang="ts">
import type { Workout } from '@/proto/api/v1/workout_service_pb'

import { useIntersectionObserver } from '@vueuse/core'
import { BoltIcon, CheckIcon, ChevronRightIcon, PlayIcon } from '@heroicons/vue/24/outline'
import { computed, nextTick, onMounted, ref } from 'vue'
import { useI18n } from 'vue-i18n'

import { listWorkouts } from '@/http/requests'
import AppSkeleton from '@/ui/components/AppSkeleton.vue'
import { useAuthStore } from '@/stores/auth'
import { useConfirmationStore } from '@/stores/confirmation'
import { useDashboardStore } from '@/stores/dashboard'
import { usePlanStore } from '@/stores/plans'
import { formatToShortDateTime } from '@/utils/datetime'
import { formatNumber } from '@/utils/numbers'
import { i18n } from '@/i18n'

// The row earns its space with the stats that matter: date, volume, duration.
const workoutMeta = (workout: Workout) => {
  const parts = [formatToShortDateTime(workout.finishedAt)]
  if (workout.intensity > 0) {
    parts.push(`${formatNumber(workout.intensity)} ${i18n.global.t('common.kg')}`)
  }
  if (workout.startedAt && workout.finishedAt) {
    const minutes = Math.max(
      1,
      Math.round(Number(workout.finishedAt.seconds - workout.startedAt.seconds) / 60),
    )
    parts.push(`${minutes} ${i18n.global.t('common.min')}`)
  }
  return parts.join(' · ')
}

const authStore = useAuthStore()
const { t } = useI18n()
const confirmationStore = useConfirmationStore()
const dashboardStore = useDashboardStore()
const planStore = usePlanStore()
const previousWorkouts = ref<Workout[]>([])
const historyPageToken = ref<Uint8Array>(new Uint8Array(0))
const historySentinel = ref<HTMLElement | null>(null)
const historyLoading = ref(false)
const historyInitiallyLoaded = ref(false)
const historyReachedEnd = ref(false)
const historyError = ref(false)
const activePlan = computed(() => dashboardStore.activePlan)
const nextRoutine = computed(() => dashboardStore.nextRoutine)
const plannedStart = computed(() =>
  nextRoutine.value
    ? {
        path: `/workouts/routine/${nextRoutine.value.id}`,
        query: activePlan.value ? { plan_id: activePlan.value.id } : {},
      }
    : '/plans',
)
const loadMoreHistory = async () => {
  if (historyLoading.value || historyReachedEnd.value || !authStore.userId) return

  historyLoading.value = true
  historyError.value = false
  const response = await listWorkouts([authStore.userId], historyPageToken.value)
  historyInitiallyLoaded.value = true

  if (!response) {
    historyError.value = true
    historyLoading.value = false
    return
  }

  const existingIds = new Set(previousWorkouts.value.map((workout) => workout.id))
  previousWorkouts.value.push(
    ...response.workouts.filter((workout) => !existingIds.has(workout.id)),
  )

  const nextPageToken = response.pagination?.nextPageToken ?? new Uint8Array(0)
  historyPageToken.value = nextPageToken
  historyReachedEnd.value = nextPageToken.length === 0
  historyLoading.value = false

  await nextTick()
  const sentinelTop = historySentinel.value?.getBoundingClientRect().top
  if (
    sentinelTop !== undefined &&
    sentinelTop <= window.innerHeight + 400 &&
    !historyReachedEnd.value
  ) {
    void loadMoreHistory()
  }
}

useIntersectionObserver(
  historySentinel,
  ([entry]) => {
    if (entry?.isIntersecting) void loadMoreHistory()
  },
  { rootMargin: '400px 0px' },
)

onMounted(async () => Promise.all([dashboardStore.load(), planStore.load(), loadMoreHistory()]))

const skip = async () => {
  if (!activePlan.value || !nextRoutine.value) return
  const confirmed = await confirmationStore.confirm({
    body: t('workout.skipConfirmBody'),
    confirmLabel: t('workout.skip'),
    title: t('workout.skipConfirmTitle', { name: nextRoutine.value.name }),
  })
  if (!confirmed) return
  if (await planStore.skip(activePlan.value.id)) await dashboardStore.load()
}
</script>

<template>
  <div class="workout-page">
    <header class="page-intro">
      <h1>{{ t('workout.heading') }}</h1>
      <p>{{ t('workout.subtitle') }}</p>
    </header>
    <section v-if="nextRoutine" class="next-card">
      <header>
        <p class="eyebrow">{{ activePlan ? t('training.activePlan') : t('home.upNext') }}</p>
        <span v-if="activePlan"
          >{{ activePlan.currentPosition + 1 }} {{ t('common.of') }}
          {{ activePlan.routines.length }}</span
        >
      </header>
      <h2>{{ nextRoutine.name }}</h2>
      <p v-if="activePlan" class="plan-name">{{ activePlan.name }}</p>
      <p>
        {{ t('home.exerciseCount', { count: nextRoutine.exercises.length }) }} ·
        {{ t('home.aboutMinutes', { count: Math.max(30, nextRoutine.exercises.length * 8) }) }}
      </p>
      <RouterLink :to="plannedStart"><PlayIcon /> {{ t('workout.startRoutine') }}</RouterLink>
      <button v-if="activePlan" type="button" class="skip-button" @click="skip">
        {{ t('workout.skipRoutine') }}
      </button>
    </section>
    <section v-else class="empty-card">
      <h2>{{ t('workout.noSelection') }}</h2>
      <p>{{ t('workout.noSelectionBody') }}</p>
      <RouterLink to="/plans">{{ t('home.chooseRoutine') }}</RouterLink>
    </section>
    <RouterLink to="/workouts/quick" class="quick-card"
      ><span class="quick-icon"><BoltIcon /></span
      ><span
        ><strong>{{ t('workout.quick') }}</strong
        ><small>{{ t('workout.quickBody') }}</small></span
      ><ChevronRightIcon
    /></RouterLink>

    <section class="workout-history">
      <header>
        <p class="eyebrow">{{ t('workout.history') }}</p>
        <h2>{{ t('workout.previous') }}</h2>
      </header>

      <div v-if="previousWorkouts.length" class="history-list">
        <RouterLink
          v-for="workout in previousWorkouts"
          :key="workout.id"
          :to="`/workouts/${workout.id}`"
        >
          <span>
            <strong>{{ workout.name }}</strong>
            <small>{{ workoutMeta(workout) }}</small>
          </span>
          <ChevronRightIcon />
        </RouterLink>
      </div>

      <AppSkeleton v-if="!historyInitiallyLoaded" />
      <div v-else-if="historyError" class="history-error" role="alert">
        <span>{{ t('workout.historyError') }}</span>
        <button type="button" @click="loadMoreHistory">{{ t('common.retry') }}</button>
      </div>
      <div v-else-if="!previousWorkouts.length" class="history-empty">
        {{ t('workout.historyEmpty') }}
      </div>
      <div v-else-if="historyLoading" class="history-status" aria-live="polite">
        <span class="history-spinner"></span> {{ t('workout.loadingMoreHistory') }}
      </div>
      <div v-else-if="historyReachedEnd" class="history-end" role="status">
        <CheckIcon /> {{ t('workout.historyEnd') }}
      </div>
      <div ref="historySentinel" class="history-sentinel" aria-hidden="true"></div>
    </section>
  </div>
</template>

<style scoped>
@reference '../../assets/base.css';

.workout-page {
  @apply space-y-4;
}
.page-intro {
  @apply px-1;
}
.eyebrow {
  @apply text-eyebrow font-bold uppercase text-text-subtle;
}
h1 {
  @apply mt-1 text-display font-bold text-text;
}
h2 {
  @apply text-title font-semibold;
}
.page-intro > p:last-child {
  @apply mt-1 text-sm text-text-subtle;
}
.quick-card {
  @apply card grid grid-cols-[1fr_auto] items-center gap-3 p-4;
}
.quick-card > span:nth-child(2) {
  @apply min-w-0;
}
.quick-card strong,
.quick-card small {
  @apply block truncate;
}
.quick-card small {
  @apply mt-1 text-xs text-text-subtle;
}
.quick-card > svg {
  @apply size-5 text-text-subtle;
}
.next-card {
  @apply rounded-sheet bg-surface-inverse p-6 text-white shadow-raised;
}
.next-card > header {
  @apply flex items-center justify-between gap-3;
}
.next-card .eyebrow {
  @apply text-ink-tint;
}
.next-card > header span {
  @apply rounded-full border border-white/20 bg-white/15 px-3 py-1 text-xs font-semibold;
}
.next-card h2 {
  @apply mt-3 text-display font-bold;
}
.next-card > p {
  @apply mt-2 text-sm text-ink-tint;
}
.next-card .plan-name {
  @apply font-semibold text-white;
}
.next-card > a {
  @apply mt-5 flex min-h-(--size-control) items-center justify-center gap-2 rounded-control bg-white px-4 text-sm font-semibold text-ink-strong;
}
.next-card > a svg {
  @apply size-5;
}
.skip-button {
  @apply mt-2 min-h-(--size-control-sm) w-full text-sm font-semibold text-ink-tint;
}
.empty-card {
  @apply card p-5;
}
.empty-card p {
  @apply mt-1 text-sm text-text-subtle;
}
.empty-card a {
  @apply mt-4 inline-flex min-h-(--size-control) items-center rounded-control bg-ink px-4 text-sm font-semibold text-white;
}
.quick-card {
  @apply grid-cols-[3rem_1fr_auto];
}
.quick-icon {
  @apply grid size-12 place-items-center rounded-control bg-ink-tint text-ink-strong;
}
.quick-icon svg {
  @apply size-6;
}
.workout-history {
  @apply pt-3;
}
.workout-history > header {
  @apply mb-3 px-1;
}
.workout-history > header h2 {
  @apply mt-1 text-text;
}
.history-list {
  @apply card overflow-hidden;
}
.history-list > a {
  @apply flex min-h-16 items-center justify-between gap-4 border-b border-border px-4 py-3 transition last:border-b-0 hover:text-ink-strong;
}
.history-list > a > span {
  @apply min-w-0;
}
.history-list strong,
.history-list small {
  @apply block truncate;
}
.history-list strong {
  @apply text-body-lg font-semibold text-text;
}
.history-list small {
  @apply mt-0.5 text-meta text-text-subtle;
}
.history-list > a > svg {
  @apply size-5 shrink-0 text-text-subtle;
}
.history-status,
.history-error,
.history-empty,
.history-end {
  @apply mt-3 flex min-h-14 items-center justify-center gap-2 rounded-control px-4 text-center text-xs text-text-subtle;
}
.history-error {
  @apply justify-between border border-danger/20 bg-danger-surface text-left text-danger;
}
.history-error button {
  @apply min-h-(--size-control-sm) shrink-0 rounded-lg bg-white px-3 font-semibold text-danger;
}
.history-empty {
  @apply card;
}
.history-end {
  @apply text-text-muted;
}
.history-end svg {
  @apply size-4 text-success;
}
.history-spinner {
  @apply size-4 animate-spin rounded-full border-2 border-border border-t-ink;
}
.history-sentinel {
  @apply h-px;
}
</style>

// web/src/ui/workouts/WorkoutView.tsx
import type { Workout } from '@/proto/api/v1/workout_service_pb'

import { BoltIcon, CheckIcon, ChevronRightIcon, PlayIcon } from '@heroicons/react/24/outline'
import { useCallback, useEffect, useRef, useState } from 'react'
import { useTranslation } from 'react-i18next'
import { Link } from 'react-router-dom'

import { listWorkouts } from '@/http/requests'
import { useAuthStore } from '@/stores/auth'
import { useConfirmationStore } from '@/stores/confirmation'
import { selectActivePlan, selectNextRoutine, useDashboardStore } from '@/stores/dashboard'
import { usePlanStore } from '@/stores/plans'
import { AppButton } from '@/ui/components/AppButton'
import { AppSkeleton } from '@/ui/components/AppSkeleton'
import { formatToShortDateTime } from '@/utils/datetime'
import { formatNumber } from '@/utils/numbers'
import { useInfiniteScroll } from '@/utils/useInfiniteScroll'
import { workoutSummary } from '@/utils/workoutSummary'
import styles from './WorkoutView.module.css'

// Matches the estimate on the home screen's up-next card.
const minutesPerExercise = 8
const minimumEstimatedMinutes = 30

// Far enough ahead that the next page is usually there by the time the reader
// reaches the end of this one.
const historyPrefetchMargin = '400px 0px'

/** The workout tab: what to train next, a quick session, and what came before. */
export const WorkoutView = () => {
  const { t } = useTranslation()

  const userId = useAuthStore((state) => state.userId)
  const activePlan = useDashboardStore(selectActivePlan)
  const nextRoutine = useDashboardStore(selectNextRoutine)

  const [workouts, setWorkouts] = useState<Workout[]>([])
  const [loading, setLoading] = useState(false)
  const [loaded, setLoaded] = useState(false)
  const [reachedEnd, setReachedEnd] = useState(false)
  const [failed, setFailed] = useState(false)

  // Held in refs rather than state: neither is rendered, and reading them from
  // state would put the loader's identity at the mercy of a render.
  const pageToken = useRef<Uint8Array>(new Uint8Array(0))
  const inFlight = useRef(false)

  const loadMoreHistory = useCallback(async () => {
    if (inFlight.current || !useAuthStore.getState().userId) return
    inFlight.current = true
    setLoading(true)
    setFailed(false)

    try {
      const response = await listWorkouts([useAuthStore.getState().userId], pageToken.current)
      setLoaded(true)

      if (!response) {
        setFailed(true)
        return
      }

      setWorkouts((current) => {
        const seen = new Set(current.map((workout) => workout.id))
        const fresh = response.workouts.filter((workout) => !seen.has(workout.id))
        return fresh.length ? [...current, ...fresh] : current
      })

      const nextPageToken = response.pagination?.nextPageToken ?? new Uint8Array(0)
      pageToken.current = nextPageToken
      setReachedEnd(nextPageToken.length === 0)
    } finally {
      inFlight.current = false
      setLoading(false)
    }
  }, [])

  useEffect(() => {
    void useDashboardStore.getState().load()
    void usePlanStore.getState().load()
    void loadMoreHistory()
  }, [loadMoreHistory])

  // Switching the observer back on after a page lands is what asks for the next
  // one while the sentinel is still in view. A failure stops that, so a failing
  // endpoint is retried by its button rather than by the scroll position.
  const sentinel = useInfiniteScroll<HTMLDivElement>(
    () => void loadMoreHistory(),
    !loading && !reachedEnd && !failed && Boolean(userId),
    historyPrefetchMargin,
  )

  const plannedStart = nextRoutine
    ? `/workouts/routine/${nextRoutine.id}${activePlan ? `?plan_id=${activePlan.id}` : ''}`
    : '/plans'

  const skip = async () => {
    if (!activePlan || !nextRoutine) return

    const confirmed = await useConfirmationStore.getState().confirm({
      body: t('workout.skipConfirmBody'),
      confirmLabel: t('workout.skip'),
      title: t('workout.skipConfirmTitle', { name: nextRoutine.name }),
    })
    if (!confirmed) return

    if (await usePlanStore.getState().skip(activePlan.id)) {
      await useDashboardStore.getState().load()
    }
  }

  // The row earns its space with the stats that matter: date, volume, duration.
  const workoutMeta = (workout: Workout) => {
    const { durationMinutes } = workoutSummary(workout)
    const parts = [formatToShortDateTime(workout.finishedAt)]

    if (workout.intensity > 0) {
      parts.push(`${formatNumber(workout.intensity)} ${t('common.kg')}`)
    }
    if (durationMinutes > 0) parts.push(`${durationMinutes} ${t('common.min')}`)

    return parts.join(' · ')
  }

  return (
    <div className={styles.workoutPage}>
      <header className={styles.pageIntro}>
        <h1>{t('workout.heading')}</h1>
        <p>{t('workout.subtitle')}</p>
      </header>

      {nextRoutine ? (
        <section className={styles.nextCard}>
          <header>
            <p className={styles.eyebrow}>
              {activePlan ? t('training.activePlan') : t('home.upNext')}
            </p>
            {activePlan && (
              <span>
                {activePlan.currentPosition + 1} {t('common.of')} {activePlan.routines.length}
              </span>
            )}
          </header>
          <h2>{nextRoutine.name}</h2>
          {activePlan && <p className={styles.planName}>{activePlan.name}</p>}
          <p>
            {t('home.exerciseCount', { count: nextRoutine.exercises.length })} ·{' '}
            {t('home.aboutMinutes', {
              count: Math.max(
                minimumEstimatedMinutes,
                nextRoutine.exercises.length * minutesPerExercise,
              ),
            })}
          </p>
          <AppButton type="link" colour="secondary" className="mt-5" to={plannedStart}>
            <PlayIcon className="size-5" aria-hidden="true" /> {t('workout.startRoutine')}
          </AppButton>
          {activePlan && (
            <AppButton
              type="button"
              colour="ghost"
              size="sm"
              className={styles.skipButton}
              onClick={() => void skip()}
            >
              {t('workout.skipRoutine')}
            </AppButton>
          )}
        </section>
      ) : (
        <section className={styles.emptyCard}>
          <h2>{t('workout.noSelection')}</h2>
          <p>{t('workout.noSelectionBody')}</p>
          <AppButton type="link" colour="primary" width="auto" className="mt-4" to="/plans">
            {t('home.chooseRoutine')}
          </AppButton>
        </section>
      )}

      <Link to="/workouts/quick" className={styles.quickCard}>
        <span className={styles.quickIcon}>
          <BoltIcon aria-hidden="true" />
        </span>
        <span>
          <strong>{t('workout.quick')}</strong>
          <small>{t('workout.quickBody')}</small>
        </span>
        <ChevronRightIcon aria-hidden="true" />
      </Link>

      <section className={styles.workoutHistory}>
        <header>
          <p className={styles.eyebrow}>{t('workout.history')}</p>
          <h2>{t('workout.previous')}</h2>
        </header>

        {workouts.length > 0 && (
          <div className={styles.historyList}>
            {workouts.map((workout) => (
              <Link key={workout.id} to={`/workouts/${workout.id}`}>
                <span>
                  <strong>{workout.name}</strong>
                  <small>{workoutMeta(workout)}</small>
                </span>
                <ChevronRightIcon aria-hidden="true" />
              </Link>
            ))}
          </div>
        )}

        {!loaded ? (
          <AppSkeleton />
        ) : failed ? (
          <div className={styles.historyError} role="alert">
            <span>{t('workout.historyError')}</span>
            <AppButton
              type="button"
              colour="destructive"
              size="sm"
              width="auto"
              onClick={() => void loadMoreHistory()}
            >
              {t('common.retry')}
            </AppButton>
          </div>
        ) : workouts.length === 0 ? (
          <div className={styles.historyEmpty}>{t('workout.historyEmpty')}</div>
        ) : loading ? (
          <div className={styles.historyStatus} aria-live="polite">
            <span className={styles.historySpinner} /> {t('workout.loadingMoreHistory')}
          </div>
        ) : (
          reachedEnd && (
            <div className={styles.historyEnd} role="status">
              <CheckIcon aria-hidden="true" /> {t('workout.historyEnd')}
            </div>
          )
        )}

        <div ref={sentinel} className={styles.historySentinel} aria-hidden="true" />
      </section>
    </div>
  )
}
