// web-next/src/ui/routines/RoutineForm.tsx
import type { Exercise } from '@/proto/api/v1/shared_pb'

import { CheckIcon, MagnifyingGlassIcon, PlusIcon } from '@heroicons/react/24/outline'
import { useCallback, useEffect, useState } from 'react'
import { useTranslation } from 'react-i18next'
import { Link } from 'react-router-dom'

import { listExercises } from '@/http/requests'
import { cn } from '@/ui/cn'
import { AppSkeleton } from '@/ui/components/AppSkeleton'
import { ExerciseTags } from '@/ui/exercises/ExerciseTags'
import { usePagination } from '@/utils/usePagination'
import styles from './RoutineForm.module.css'

interface Props {
  submitLabel: string
  onSave: (name: string, exerciseIds: string[]) => void
  saving?: boolean
  initialName?: string
  initialExerciseIds?: string[]
}

/**
 * The fields a routine is made of, shared by creating one and editing one.
 *
 * The caller mounts it only once it has the routine to edit, so the initial
 * values are read once and owned here from then on.
 */
export const RoutineForm = ({
  submitLabel,
  onSave,
  saving = false,
  initialName = '',
  initialExerciseIds,
}: Props) => {
  const { t } = useTranslation()
  const { hasMorePages, currentPageToken, setFromResponse } = usePagination()

  const [name, setName] = useState(initialName)
  const [selectedIds, setSelectedIds] = useState<string[]>(() => initialExerciseIds ?? [])
  const [exercises, setExercises] = useState<Exercise[]>([])
  const [search, setSearch] = useState('')
  const [loading, setLoading] = useState(true)

  const fetchExercises = useCallback(async () => {
    const response = await listExercises(currentPageToken())
    if (!response) return

    setExercises((current) => [...current, ...response.exercises])
    setFromResponse(response.pagination)
  }, [currentPageToken, setFromResponse])

  useEffect(() => {
    const load = async () => {
      await fetchExercises()
      setLoading(false)
    }
    void load()
  }, [fetchExercises])

  const query = search.trim().toLowerCase()
  const filtered = query
    ? exercises.filter((exercise) =>
        [exercise.name, ...exercise.tags].join(' ').toLowerCase().includes(query),
      )
    : exercises

  // A routine with no name or no exercises is not a routine yet.
  const canSubmit = name.trim().length > 0 && selectedIds.length > 0 && !saving

  const toggleExercise = (exerciseId: string) =>
    setSelectedIds((current) =>
      current.includes(exerciseId)
        ? current.filter((id) => id !== exerciseId)
        : [...current, exerciseId],
    )

  return (
    <form
      className={styles.routineForm}
      onSubmit={(event) => {
        event.preventDefault()
        if (canSubmit) onSave(name.trim(), selectedIds)
      }}
    >
      <header className={styles.formIntro}>
        <div>
          <p className={styles.eyebrow}>{t('routine.form.eyebrow')}</p>
          <p>{t('routine.form.intro')}</p>
        </div>
        <span className={styles.selectionCount}>
          {t('routine.form.selectedCount', { count: selectedIds.length })}
        </span>
      </header>

      <section className={styles.formCard}>
        <label className={styles.fieldLabel} htmlFor="routine-name">
          {t('routine.form.name')}
        </label>
        <input
          id="routine-name"
          className={styles.nameInput}
          type="text"
          required
          autoComplete="off"
          placeholder={t('routine.form.namePlaceholder')}
          value={name}
          onChange={(event) => setName(event.target.value)}
        />
      </section>

      <section className={styles.exerciseCard}>
        <div className={styles.exerciseToolbar}>
          <div>
            <h2>{t('common.exercises')}</h2>
            <p>{t('routine.form.selectHelp')}</p>
          </div>
          <label className={styles.searchField}>
            <MagnifyingGlassIcon aria-hidden="true" />
            <input
              type="search"
              placeholder={t('common.search')}
              aria-label={t('exercise.search')}
              value={search}
              onChange={(event) => setSearch(event.target.value)}
            />
          </label>
        </div>

        {loading ? (
          <AppSkeleton />
        ) : filtered.length > 0 ? (
          <div className={styles.exerciseGrid}>
            {filtered.map((exercise) => {
              const selected = selectedIds.includes(exercise.id)

              return (
                <button
                  key={exercise.id}
                  type="button"
                  className={cn(styles.exerciseOption, selected && styles.selected)}
                  aria-pressed={selected}
                  onClick={() => toggleExercise(exercise.id)}
                >
                  <span className={styles.checkBox}>
                    {selected && <CheckIcon aria-hidden="true" />}
                  </span>
                  <span className={styles.exerciseCopy}>
                    <strong>{exercise.name}</strong>
                    <ExerciseTags compact tags={exercise.tags} />
                  </span>
                </button>
              )
            })}
          </div>
        ) : (
          <div className={styles.emptyRow}>
            {search ? t('workout.noExerciseMatches') : t('routine.form.createFirst')}
          </div>
        )}

        {hasMorePages && (
          <button className={styles.loadMore} type="button" onClick={() => void fetchExercises()}>
            <PlusIcon aria-hidden="true" /> {t('exercise.loadMore')}
          </button>
        )}
      </section>

      <div className={styles.formActions}>
        <Link to="/routines" className={styles.cancelLink}>
          {t('common.cancel')}
        </Link>
        <button className={styles.saveButton} type="submit" disabled={!canSubmit}>
          {saving ? t('training.planForm.saving') : submitLabel}
        </button>
      </div>
    </form>
  )
}

// web/src/ui/routines/RoutineForm.vue
<script setup lang="ts">
import { computed, onMounted, ref, watch } from 'vue'
import { useI18n } from 'vue-i18n'
import { CheckIcon, MagnifyingGlassIcon, PlusIcon } from '@heroicons/vue/24/outline'

import { listExercises } from '@/http/requests'
import type { Exercise } from '@/proto/api/v1/shared_pb'
import usePagination from '@/utils/usePagination'
import AppSkeleton from '@/ui/components/AppSkeleton.vue'
import ExerciseTags from '@/ui/exercises/ExerciseTags.vue'

const { t } = useI18n()

const props = withDefaults(
  defineProps<{
    initialName?: string
    initialExerciseIds?: string[]
    saving?: boolean
    submitLabel: string
  }>(),
  {
    initialName: '',
    initialExerciseIds: () => [],
    saving: false,
  },
)

const emit = defineEmits<{
  save: [name: string, exerciseIds: string[]]
}>()

const name = ref(props.initialName)
const exercises = ref<Exercise[]>([])
const selectedIds = ref<string[]>([...props.initialExerciseIds])
const search = ref('')
const loading = ref(true)
const { hasMorePages, pageToken, resolvePageToken } = usePagination()

watch(
  () => props.initialName,
  (value) => (name.value = value),
)

watch(
  () => props.initialExerciseIds,
  (value) => (selectedIds.value = [...value]),
  { deep: true },
)

onMounted(async () => {
  await fetchExercises()
  loading.value = false
})

const filteredExercises = computed(() => {
  const query = search.value.trim().toLowerCase()
  if (!query) return exercises.value

  return exercises.value.filter((exercise) =>
    [exercise.name, ...exercise.tags].join(' ').toLowerCase().includes(query),
  )
})

const canSubmit = computed(
  () => name.value.trim().length > 0 && selectedIds.value.length > 0 && !props.saving,
)

const fetchExercises = async () => {
  const response = await listExercises(pageToken.value)
  if (!response) return

  exercises.value = [...exercises.value, ...response.exercises]
  pageToken.value = resolvePageToken(response.pagination)
}

const toggleExercise = (exerciseId: string) => {
  selectedIds.value = selectedIds.value.includes(exerciseId)
    ? selectedIds.value.filter((id) => id !== exerciseId)
    : [...selectedIds.value, exerciseId]
}

const submit = () => {
  if (!canSubmit.value) return
  emit('save', name.value.trim(), selectedIds.value)
}
</script>

<template>
  <form class="routine-form" @submit.prevent="submit">
    <header class="form-intro">
      <div>
        <p class="eyebrow">{{ t('routine.form.eyebrow') }}</p>
        <p>{{ t('routine.form.intro') }}</p>
      </div>
      <span class="selection-count">{{
        t('routine.form.selectedCount', { count: selectedIds.length })
      }}</span>
    </header>

    <section class="form-card">
      <label class="field-label" for="routine-name">{{ t('routine.form.name') }}</label>
      <input
        id="routine-name"
        v-model="name"
        class="name-input"
        type="text"
        required
        autocomplete="off"
        :placeholder="t('routine.form.namePlaceholder')"
      />
    </section>

    <section class="exercise-card">
      <div class="exercise-toolbar">
        <div>
          <h2>{{ t('common.exercises') }}</h2>
          <p>{{ t('routine.form.selectHelp') }}</p>
        </div>
        <label class="search-field">
          <MagnifyingGlassIcon />
          <input
            v-model="search"
            type="search"
            :placeholder="t('common.search')"
            :aria-label="t('exercise.search')"
          />
        </label>
      </div>

      <AppSkeleton v-if="loading" />
      <div v-else-if="filteredExercises.length" class="exercise-grid">
        <button
          v-for="exercise in filteredExercises"
          :key="exercise.id"
          type="button"
          class="exercise-option"
          :class="{ selected: selectedIds.includes(exercise.id) }"
          :aria-pressed="selectedIds.includes(exercise.id)"
          @click="toggleExercise(exercise.id)"
        >
          <span class="check-box">
            <CheckIcon v-if="selectedIds.includes(exercise.id)" />
          </span>
          <span class="exercise-copy">
            <strong>{{ exercise.name }}</strong>
            <ExerciseTags compact :tags="exercise.tags" />
          </span>
        </button>
      </div>
      <div v-else class="empty-row">
        {{ search ? t('workout.noExerciseMatches') : t('routine.form.createFirst') }}
      </div>

      <button v-if="hasMorePages" class="load-more" type="button" @click="fetchExercises">
        <PlusIcon /> {{ t('exercise.loadMore') }}
      </button>
    </section>

    <div class="form-actions">
      <RouterLink to="/routines" class="cancel-link">{{ t('common.cancel') }}</RouterLink>
      <button class="save-button" type="submit" :disabled="!canSubmit">
        {{ saving ? t('training.planForm.saving') : submitLabel }}
      </button>
    </div>
  </form>
</template>

<style scoped>
@reference '../../assets/base.css';

.routine-form {
  @apply mx-auto max-w-4xl space-y-5;
}
.form-intro {
  @apply flex flex-col gap-3 px-1 sm:flex-row sm:items-end sm:justify-between;
}
.eyebrow {
  @apply text-eyebrow font-bold uppercase text-text-subtle;
}
.form-intro p:last-child {
  @apply mt-2 text-sm text-text-subtle;
}
.selection-count {
  @apply w-max rounded-full bg-ink-surface px-3 py-1.5 text-xs font-semibold text-ink-strong;
}
.form-card,
.exercise-card {
  @apply card p-5;
}
.field-label {
  @apply mb-2 block text-sm font-semibold text-text-muted;
}
.name-input {
  @apply h-12 w-full rounded-control border border-border bg-ink-surface px-4 text-base font-medium text-text placeholder:text-text-subtle focus:border-ink-muted focus:bg-surface focus:ring-2 focus:ring-ink-tint;
}
.exercise-toolbar {
  @apply mb-4 flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between;
}
.exercise-toolbar h2 {
  @apply text-title font-semibold text-text;
}
.exercise-toolbar p {
  @apply mt-1 text-sm text-text-subtle;
}
.search-field {
  @apply flex min-w-52 items-center gap-2 rounded-control border border-border bg-ink-surface px-3;
}
.search-field svg {
  @apply size-5 text-text-subtle;
}
.search-field input {
  @apply h-11 w-full border-0 bg-transparent p-0 text-sm focus:ring-0;
}
.exercise-grid {
  @apply grid gap-2 sm:grid-cols-2;
}
.exercise-option {
  @apply flex min-h-16 items-center gap-3 rounded-control border border-border px-4 py-3 text-left transition hover:border-ink-border hover:bg-ink-surface/40;
}
.exercise-option.selected {
  @apply border-ink-border bg-ink-surface;
}
.check-box {
  @apply grid size-6 shrink-0 place-items-center rounded-md border-2 border-ink-border bg-white;
}
.selected .check-box {
  @apply border-ink bg-ink text-white;
}
.check-box svg {
  @apply size-4 stroke-[3];
}
.exercise-copy {
  @apply min-w-0;
}
.exercise-copy strong {
  @apply block truncate text-sm font-semibold text-text;
}
.exercise-copy small {
  @apply mt-0.5 block truncate text-xs text-text-subtle;
}
.empty-row {
  @apply rounded-control bg-ink-surface p-6 text-center text-sm text-text-subtle;
}
.load-more {
  @apply mt-4 inline-flex min-h-(--size-control) items-center gap-2 rounded-control border border-border px-4 text-sm font-semibold text-text-muted hover:bg-ink-surface;
}
.load-more svg {
  @apply size-4;
}
.form-actions {
  @apply sticky bottom-20 z-10 flex items-center justify-end gap-3 rounded-card border border-border bg-white/95 p-3 shadow-raised backdrop-blur md:bottom-4;
}
.cancel-link {
  @apply inline-flex min-h-(--size-control) items-center rounded-control px-4 text-sm font-semibold text-text-muted hover:bg-ink-surface;
}
.save-button {
  @apply inline-flex min-h-(--size-control) items-center rounded-control bg-ink px-5 text-sm font-semibold text-white hover:bg-ink-strong disabled:cursor-not-allowed disabled:bg-ink-border;
}
</style>
