// web/src/ui/components/AppList.vue
<script setup lang="ts">
import { vInfiniteScroll } from '@vueuse/components'
import { ArrowPathIcon } from '@heroicons/vue/24/outline'

defineProps<{
  canFetch?: boolean
}>()

const emits = defineEmits(['fetch'])

const onFetch = async () => {
  emits('fetch')
}
</script>

<template>
  <ul role="list">
    <slot />
    <li v-if="canFetch" v-infinite-scroll="onFetch" class="fetching">
      <ArrowPathIcon class="size-7 animate-spin" />
    </li>
  </ul>
</template>

<style scoped>
ul {
  @apply mb-4 divide-y divide-slate-100 overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm;

  li.fetching {
    @apply flex h-16 items-center justify-center text-slate-700;
  }
}
</style>

// web-next/src/ui/components/AppList.tsx
import { ArrowPathIcon } from '@heroicons/react/24/outline'
import type { ReactNode } from 'react'
import { useInfiniteScroll } from '@/utils/useInfiniteScroll'

export default function AppList({
  canFetch,
  children,
  onFetch,
}: {
  canFetch?: boolean
  children: ReactNode
  onFetch?: () => void
}) {
  const sentinelRef = useInfiniteScroll<HTMLLIElement>(
    () => onFetch?.(),
    Boolean(canFetch && onFetch),
  )

  return (
    <ul className="card mb-4 divide-y divide-border overflow-hidden" role="list">
      {children}
      {canFetch && (
        <li ref={sentinelRef} className="flex h-16 items-center justify-center text-text-muted">
          <ArrowPathIcon className="size-7 animate-spin" />
        </li>
      )}
    </ul>
  )
}
