// web-next/src/ui/NotFound.tsx
import { useTranslation } from 'react-i18next'

export const NotFound = () => {
  const { t } = useTranslation()

  return (
    <div className="p-4 text-center">
      <h1 className="mt-4 text-balance text-5xl font-semibold tracking-tight text-text-muted">
        {t('notFound.title')}
      </h1>
      <p className="mt-6 text-pretty text-lg font-medium text-text-subtle">{t('notFound.body')}</p>
    </div>
  )
}

// js/src/views/NotFound.vue
<script setup lang="ts">
import { RouterLink } from 'vue-router'
</script>

<template>
  <div class="text-center">
    <h1 class="mt-4 text-balance text-5xl font-semibold tracking-tight text-gray-700 sm:text-7xl">Page not found</h1>
    <p class="mt-6 text-pretty text-lg font-medium text-gray-500 sm:text-xl/8">Sorry, we couldn’t find the page you’re looking for.</p>
  </div>
</template>
