// web/src/ui/components/CardWorkoutExercise.vue
<script setup lang="ts">
import { ExerciseMetric, type Set } from '@/proto/api/v1/shared_pb'
import { useI18n } from 'vue-i18n'
import { TrophyIcon } from '@heroicons/vue/24/solid'
import ExerciseTags from '@/ui/exercises/ExerciseTags.vue'
import {
  exerciseMetrics,
  formatExerciseSet,
  formatMeasurementDuration,
  measurementDefinitions,
} from '@/utils/exerciseMeasurements'
import { weightUnitLabel } from '@/utils/weightUnits'
import { distanceUnitLabel } from '@/utils/distanceUnits'

const { t } = useI18n()

const props = withDefaults(
  defineProps<{
    compact?: boolean
    flat?: boolean
    exerciseId?: string
    name?: string
    sets: Set[]
    tags?: string[]
    metrics?: ExerciseMetric[]
  }>(),
  { compact: false, flat: false, tags: () => [] },
)

const metrics = exerciseMetrics({ metrics: props.metrics ?? [] })
const measurements = measurementDefinitions.filter(({ metric }) => metrics.includes(metric))

const formatValue = (set: Set, field: (typeof measurementDefinitions)[number]['field']) => {
  const value = set[field]
  if (field === 'durationSeconds') return formatMeasurementDuration(value)
  return new Intl.NumberFormat(undefined, { maximumFractionDigits: 2 }).format(value)
}

const columnLabel = (metric: ExerciseMetric) => {
  const definition = measurementDefinitions.find((measurement) => measurement.metric === metric)
  return definition ? t(definition.labelKey) : undefined
}
</script>

<template>
  <article class="exercise-block" :class="{ compact, flat }">
    <header>
      <div>
        <RouterLink :to="`/exercises/${exerciseId}`">{{ name }}</RouterLink>
        <ExerciseTags compact :tags="tags" />
      </div>
      <span v-if="!compact" class="set-count">
        {{ sets.length }} {{ sets.length === 1 ? 'set' : 'sets' }}
      </span>
    </header>

    <div
      class="set-table"
      role="table"
      :aria-label="`${name} sets`"
      :style="{ '--metric-count': measurements.length }"
    >
      <div v-if="!compact" class="set-row table-head" role="row">
        <span role="columnheader">Set</span>
        <span v-for="measurement in measurements" :key="measurement.field" role="columnheader">
          {{ columnLabel(measurement.metric) }}
        </span>
      </div>
      <div v-for="(set, index) in sets" :key="set.id || index" class="set-row" role="row">
        <span
          class="set-number"
          :class="{ 'personal-best': !compact && set.metadata?.personalBest }"
          role="cell"
          :aria-label="
            set.metadata?.personalBest ? `Set ${index + 1}, personal best` : `Set ${index + 1}`
          "
        >
          <template v-if="compact">{{ index + 1 }}</template>
          <TrophyIcon v-else-if="set.metadata?.personalBest" aria-hidden="true" />
          <template v-else>{{ index + 1 }}</template>
        </span>
        <span v-if="compact" class="compact-set-value" role="cell">
          <strong>{{ formatExerciseSet(set, { metrics }) }}</strong>
          <span
            v-if="set.metadata?.personalBest"
            class="compact-personal-best"
            role="img"
            aria-label="Personal best"
          >
            <TrophyIcon aria-hidden="true" />
          </span>
        </span>
        <template v-else>
          <span v-for="measurement in measurements" :key="measurement.field" role="cell">
            <strong>{{ formatValue(set, measurement.field) }}</strong>
            <small v-if="measurement.field === 'weight'">
              {{ weightUnitLabel(set.weightUnit) }}
            </small>
            <small v-else-if="measurement.field === 'distance'">
              {{ distanceUnitLabel(set.distanceUnit) }}
            </small>
          </span>
        </template>
      </div>
    </div>
  </article>
</template>

<style scoped>
@reference '../../assets/base.css';

.exercise-block {
  @apply card shadow-none overflow-hidden;
}
.exercise-block > header {
  @apply flex items-center justify-between gap-3 border-b border-slate-100 px-4 py-3 sm:px-5;
}
.exercise-block > header > div {
  @apply flex min-w-0 items-center gap-2;
}
.exercise-block > header a {
  @apply -mx-1.5 -my-2.5 inline-flex min-h-(--size-control-sm) items-center truncate px-1.5 py-2.5 text-base font-semibold text-slate-950 transition hover:text-ink-strong;
}
.set-count {
  @apply shrink-0 text-xs font-medium text-slate-500;
}
.set-table {
  @apply px-4 py-2 sm:px-5;
}
.set-row {
  grid-template-columns: 2.25rem repeat(var(--metric-count), minmax(4.5rem, 1fr));
  @apply grid min-h-11 items-center gap-2 border-t border-slate-100 text-sm first:border-t-0;
}
.table-head {
  @apply min-h-9 border-0 text-eyebrow font-semibold uppercase text-text-subtle;
}
.set-number {
  @apply grid size-7 place-items-center rounded-lg bg-info-surface text-xs font-semibold text-text-muted;
}
.set-number.personal-best {
  @apply bg-record-surface text-record-strong;
}
.set-number.personal-best svg {
  @apply size-4;
}
.set-row strong {
  @apply font-semibold text-slate-900;
}
.set-row small {
  @apply ml-1 text-meta font-normal text-text-muted;
}
.set-volume {
  @apply text-slate-500;
}
.flat {
  @apply rounded-none border-0;
}
.flat > header {
  @apply px-0 py-3;
}
.flat .set-table {
  @apply px-0 pb-4 pt-2;
}
.compact {
  @apply rounded-none border-0 bg-transparent py-3;
}
.compact > header {
  @apply min-w-0 border-0 px-0 py-0;
}
.compact > header a {
  @apply text-[0.9375rem];
}
.compact .set-table {
  @apply mt-1 flex flex-wrap items-center gap-x-5 gap-y-1 px-0 py-0;
}
.compact .set-row {
  @apply min-h-8 grid-cols-[1.75rem_auto] justify-start gap-2 border-0;
}
.compact .set-number {
  @apply size-6;
}
.compact .set-row small {
  @apply text-text-muted;
}
.compact-set-value {
  @apply inline-flex items-center gap-1.5 whitespace-nowrap text-sm text-slate-900;
}
.compact-set-value > span {
  @apply font-medium;
}
.compact-set-value .compact-personal-best {
  @apply ml-0.5 grid size-6 place-items-center rounded-lg bg-record-surface text-record-strong;
}
.compact-personal-best svg {
  @apply size-4;
}
@media (max-width: 520px) {
  .set-row {
    grid-template-columns: 2rem repeat(var(--metric-count), minmax(3.75rem, 1fr));
    @apply gap-1.5;
  }
  .set-row,
  .table-head {
    @apply text-xs;
  }
}
</style>

// web/src/ui/features/CardWorkoutExercise.tsx
import type { ExerciseMetric, Set } from '@/proto/api/v1/shared_pb'
import type { CSSProperties } from 'react'

import { ChevronDownIcon } from '@heroicons/react/24/outline'
import { TrophyIcon } from '@heroicons/react/24/solid'
import { useId, useState } from 'react'
import { useTranslation } from 'react-i18next'

import { cn } from '@/ui/cn'
import { AppButton } from '@/ui/components/AppButton'
import { AppOptionRow } from '@/ui/components/AppOptionRow'
import { distanceUnitLabel } from '@/utils/distanceUnits'
import {
  exerciseMetrics,
  formatDurationDisplay,
  formatSetPace,
  isDistanceTimeExercise,
  measurementDefinitions,
} from '@/utils/exerciseMeasurements'
import { formatNumber } from '@/utils/numbers'
import { weightUnitLabel } from '@/utils/weightUnits'
import styles from './CardWorkoutExercise.module.css'

type Measurement = (typeof measurementDefinitions)[number]

const formatValue = (set: Set, field: Measurement['field']) =>
  field === 'durationSeconds' ? formatDurationDisplay(set[field]) : formatNumber(set[field], 2)

interface Props {
  sets: Set[]
  exerciseId?: string
  name?: string
  metrics?: ExerciseMetric[]
  /** The session opens on its first exercise, so the card is never all rows. */
  defaultOpen?: boolean
}

/**
 * One exercise of a finished workout: a row that opens onto its sets.
 *
 * A six-exercise session printed six SET / WEIGHT / REPS tables and ran to
 * several screens of near-identical rows, so what the session was is now the
 * list of names, and the numbers are one tap away.
 */
export const CardWorkoutExercise = ({
  sets,
  exerciseId,
  name,
  metrics: exerciseMetricList,
  defaultOpen = false,
}: Props) => {
  const { t } = useTranslation()

  const panelId = useId()
  const [open, setOpen] = useState(defaultOpen)

  const metrics = exerciseMetrics({ metrics: exerciseMetricList ?? [] })
  const measurements = measurementDefinitions.filter(({ metric }) => metrics.includes(metric))
  const showPace = isDistanceTimeExercise({ metrics })
  const hasPersonalBest = sets.some((set) => set.metadata?.personalBest)

  const columnLabel = (metric: ExerciseMetric) => {
    const definition = measurementDefinitions.find((measurement) => measurement.metric === metric)
    return definition ? t(definition.labelKey) : undefined
  }

  return (
    <article className={styles.exercise}>
      <AppOptionRow
        className={styles.summary}
        aria-expanded={open}
        aria-controls={panelId}
        trailing={
          <ChevronDownIcon
            className={cn(styles.caret, open && styles.caretOpen)}
            aria-hidden="true"
          />
        }
        onClick={() => setOpen((shown) => !shown)}
      >
        <span className={styles.summaryCopy}>
          <span className={styles.name}>{name}</span>
          {/* The marker is on the row rather than only inside it: what a reader
              scans this list for is which exercises went well. */}
          {hasPersonalBest && (
            <span className={styles.personalBestBadge}>
              <TrophyIcon aria-hidden="true" />
              {t('workout.personalBest')}
            </span>
          )}
          <span className={styles.setCount}>
            {t('workout.setsCompact', { count: sets.length })}
          </span>
        </span>
      </AppOptionRow>

      {open && (
        <div id={panelId} className={styles.panel}>
          <div
            className={styles.setTable}
            role="table"
            aria-label={t('workout.setsTableAria', { name })}
            style={{ '--metric-count': measurements.length + (showPace ? 1 : 0) } as CSSProperties}
          >
            <div className={cn(styles.setRow, styles.tableHead)} role="row">
              <span role="columnheader">{t('common.set')}</span>
              {measurements.map((measurement) => (
                <span key={measurement.field} role="columnheader">
                  {columnLabel(measurement.metric)}
                </span>
              ))}
              {showPace && <span role="columnheader">{t('common.pace')}</span>}
            </div>

            {sets.map((set, index) => {
              const personalBest = Boolean(set.metadata?.personalBest)

              return (
                <div
                  key={set.id || index}
                  className={cn(styles.setRow, personalBest && styles.personalBestRow)}
                  role="row"
                >
                  {/* The number stays on a record set: it was the one row where
                      a reader could not tell which set they were looking at. */}
                  <span
                    className={cn(styles.setNumber, personalBest && styles.personalBest)}
                    role="cell"
                    aria-label={
                      personalBest
                        ? t('workout.setPersonalBestAria', { number: index + 1 })
                        : t('workout.setNumberAria', { number: index + 1 })
                    }
                  >
                    {index + 1}
                  </span>

                  {measurements.map((measurement) => (
                    <span key={measurement.field} role="cell">
                      <strong>{formatValue(set, measurement.field)}</strong>
                      {measurement.field === 'weight' && (
                        <small>{weightUnitLabel(set.weightUnit)}</small>
                      )}
                      {measurement.field === 'distance' && (
                        <small>{distanceUnitLabel(set.distanceUnit)}</small>
                      )}
                    </span>
                  ))}
                  {showPace && (
                    <span className={styles.setPace} role="cell">
                      {formatSetPace(set) ?? '—'}
                    </span>
                  )}

                  {/* A tint is not a label: the trophy is what says record to a
                      reader who cannot tell this row's colour from the next. */}
                  {personalBest && (
                    <span
                      className={styles.personalBestMark}
                      role="cell"
                      aria-label={t('workout.personalBest')}
                    >
                      <TrophyIcon aria-hidden="true" />
                    </span>
                  )}
                </div>
              )
            })}
          </div>

          <AppButton
            type="link"
            colour="ghost"
            size="inline"
            width="auto"
            className={styles.viewExercise}
            to={`/exercises/${exerciseId}`}
          >
            {t('workout.viewExercise')}
          </AppButton>
        </div>
      )}
    </article>
  )
}
