// web/src/ui/components/WorkoutChart.vue
<script setup lang="ts">
import type { Workout } from '@/proto/api/v1/workout_service_pb.ts'
import { computed } from 'vue'
import { Bar as BarChart } from 'vue-chartjs'
import { DateTime } from 'luxon'
import { BarElement, Chart as ChartJS, CategoryScale, LinearScale, Tooltip } from 'chart.js'

ChartJS.register(Tooltip, BarElement, CategoryScale, LinearScale)

const props = defineProps<{
  workouts: Workout[]
}>()

const options = {
  maintainAspectRatio: false,
  responsive: true,
  scales: {
    x: {
      legend: {
        display: false,
      },
      grid: {
        display: false,
        drawBorder: true,
      },
      ticks: {
        display: true,
        maxTicksLimit: 7,
        color: '#64748b',
      },
      title: {
        display: false,
      },
    },
    y: {
      legend: {
        display: false,
      },
      grid: {
        color: '#e2e8f0',
        drawBorder: false,
      },
      ticks: {
        display: true,
        color: '#64748b',
      },
      title: {
        display: true,
        text: 'Volume (kg)',
        color: '#64748b',
      },
      beginAtZero: true,
    },
  },
  plugins: {
    legend: { display: false },
  },
}

const dailyVolume = computed(() => {
  const buckets = new Map<string, { label: string; timestamp: number; volume: number }>()

  props.workouts.forEach((workout) => {
    if (!workout.finishedAt) return
    const finishedAt = DateTime.fromSeconds(Number(workout.finishedAt.seconds))
    if (!finishedAt.isValid) return

    const key = finishedAt.toISODate()
    if (!key) return
    const existing = buckets.get(key)
    buckets.set(key, {
      label: finishedAt.toFormat('d LLL'),
      timestamp: finishedAt.toMillis(),
      volume: (existing?.volume ?? 0) + workout.intensity,
    })
  })

  return [...buckets.values()].sort((first, second) => first.timestamp - second.timestamp)
})

const data = computed(() => {
  return {
    datasets: [
      {
        backgroundColor: '#25282d',
        borderRadius: 8,
        data: dailyVolume.value.map((day) => day.volume),
        label: 'Training volume',
      },
    ],
    labels: dailyVolume.value.map((day) => day.label),
  }
})
</script>

<template>
  <div class="chart-frame">
    <BarChart
      :data="data"
      :options="options as any"
      aria-label="Training volume by day"
      role="img"
    />
  </div>
</template>

<style scoped>
.chart-frame {
  @apply h-64;
}
</style>

// web/src/ui/features/WorkoutChart.tsx
import type { Workout } from '@/proto/api/v1/workout_service_pb'
import type { ChartOptions } from 'chart.js'

import { BarElement, CategoryScale, Chart as ChartJS, LinearScale, Tooltip } from 'chart.js'
import { useMemo } from 'react'
import { Bar } from 'react-chartjs-2'
import { useTranslation } from 'react-i18next'

import { borderColor, inkColor, subtleColor, successColor } from '@/ui/chartTokens'
import { latestValueLabel } from '@/ui/features/latestValueLabel'
import { dailyVolume } from '@/utils/dailyVolume'
import styles from './WorkoutChart.module.css'

ChartJS.register(Tooltip, BarElement, CategoryScale, LinearScale)

interface Props {
  workouts: Workout[]
}

/** Daily training volume as bars, with the most recent day picked out. */
export const WorkoutChart = ({ workouts }: Props) => {
  const { t } = useTranslation()

  const days = useMemo(() => dailyVolume(workouts), [workouts])

  const options: ChartOptions<'bar'> = {
    maintainAspectRatio: false,
    responsive: true,
    layout: {
      // Room for the value label above the tallest bar.
      padding: { top: 14 },
    },
    scales: {
      x: {
        grid: { display: false },
        ticks: { display: true, maxTicksLimit: 7, color: subtleColor },
        title: { display: false },
      },
      y: {
        grid: { color: borderColor },
        ticks: { display: true, color: subtleColor },
        title: { display: true, text: t('progress.volumeAxis'), color: subtleColor },
        beginAtZero: true,
      },
    },
    plugins: {
      legend: { display: false },
    },
  }

  const data = {
    labels: days.map((day) => day.label),
    datasets: [
      {
        // The most recent day picks up momentum green.
        backgroundColor: days.map((_, index) =>
          index === days.length - 1 ? successColor : inkColor,
        ),
        borderRadius: 8,
        data: days.map((day) => day.volume),
        label: t('progress.trainingVolume'),
      },
    ],
  }

  return (
    <div className={styles.frame}>
      <Bar
        data={data}
        options={options}
        plugins={[latestValueLabel]}
        aria-label={t('progress.volumeChartAria')}
        role="img"
      />
    </div>
  )
}
