// web/src/ui/plans/PlansView.vue
<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { useI18n } from 'vue-i18n'
import { ArrowPathIcon, CheckIcon, PlusIcon } from '@heroicons/vue/24/outline'

import { useDashboardStore } from '@/stores/dashboard'
import { usePlanStore } from '@/stores/plans'
import TrainingTabs from '@/ui/components/TrainingTabs.vue'

const planStore = usePlanStore()
const { t } = useI18n()
const dashboardStore = useDashboardStore()
const plansLoaded = ref(false)

const activePlan = computed(() => planStore.activePlan)
const otherPlans = computed(() => planStore.plans.filter((plan) => !plan.active))
const nextRoutine = computed(() => {
  const plan = activePlan.value
  return plan?.routines[plan.currentPosition]
})
onMounted(async () => {
  await planStore.load()
  plansLoaded.value = true
})

const activate = async (id: string) => {
  if (activePlan.value && !confirm(t('training.activateConfirm'))) return
  if (await planStore.activate(id)) await dashboardStore.load()
}

const pause = async () => {
  if (!confirm(t('training.pauseConfirm'))) return
  if (await planStore.pause()) await dashboardStore.load()
}
</script>

<template>
  <div class="plans-page">
    <header class="page-intro">
      <div>
        <p class="eyebrow">{{ t('training.eyebrow') }}</p>
        <h1>{{ t('training.heading') }}</h1>
      </div>
      <RouterLink v-if="planStore.plans.length" to="/plans/create"
        ><PlusIcon /> {{ t('training.newPlan') }}</RouterLink
      >
      <p>{{ t('training.plansDescription') }}</p>
    </header>

    <TrainingTabs />

    <section v-if="!plansLoaded" class="plan-loading" aria-live="polite">
      <span></span><span></span><span></span>
    </section>

    <section v-else-if="!planStore.plans.length" class="empty-plan-state">
      <span class="empty-plan-icon"><ArrowPathIcon /></span>
      <p class="eyebrow">{{ t('training.howPlansWork') }}</p>
      <h2>{{ t('training.repeatingTitle') }}</h2>
      <p class="empty-plan-copy">
        {{ t('training.repeatingBody') }}
      </p>

      <ol class="plan-steps">
        <li>
          <span>1</span>
          <div>
            <strong>{{ t('training.chooseRoutines') }}</strong
            ><small>{{ t('training.chooseRoutinesBody') }}</small>
          </div>
        </li>
        <li>
          <span>2</span>
          <div>
            <strong>{{ t('training.activatePlan') }}</strong
            ><small>{{ t('training.activatePlanBody') }}</small>
          </div>
        </li>
        <li>
          <span><CheckIcon /></span>
          <div>
            <strong>{{ t('training.keepTraining') }}</strong
            ><small>{{ t('training.keepTrainingBody') }}</small>
          </div>
        </li>
      </ol>

      <p class="active-plan-rule">
        {{ t('training.oneActive') }}
      </p>
      <RouterLink to="/plans/create" class="first-plan-button">
        <PlusIcon /> {{ t('training.createFirstPlan') }}
      </RouterLink>
    </section>

    <template v-else>
      <section v-if="activePlan" class="active-plan">
        <header>
          <p class="eyebrow">{{ t('training.activePlan') }}</p>
          <span>{{ t('training.active') }}</span>
        </header>
        <h2>{{ activePlan.name }}</h2>
        <p>{{ t('training.routineCountRepeats', { count: activePlan.routines.length }) }}</p>
        <div class="position-row">
          <span>{{ t('training.currentPosition') }}</span
          ><strong>{{
            t('training.routinePosition', {
              current: activePlan.currentPosition + 1,
              total: activePlan.routines.length,
            })
          }}</strong>
        </div>
        <div class="sequence" aria-label="Current plan position">
          <span
            v-for="(_, index) in activePlan.routines"
            :key="index"
            :class="{
              current: index === activePlan.currentPosition,
              done: index < activePlan.currentPosition,
            }"
            >{{ index + 1 }}</span
          >
        </div>
        <div v-if="nextRoutine" class="next-row">
          <div>
            <small>{{ t('home.upNext') }}</small
            ><strong>{{ nextRoutine.name }}</strong
            ><small>{{ t('home.exerciseCount', { count: nextRoutine.exercises.length }) }}</small>
          </div>
        </div>
        <footer>
          <RouterLink :to="`/plans/${activePlan.id}`">{{ t('training.viewPlan') }}</RouterLink
          ><button type="button" @click="pause">{{ t('training.pause') }}</button>
        </footer>
      </section>

      <section v-else class="paused-note">
        <h2>{{ t('training.noActivePlan') }}</h2>
        <p>{{ t('training.noActivePlanBody') }}</p>
      </section>

      <section v-if="otherPlans.length" class="other-plans">
        <header>
          <p class="eyebrow">{{ t('training.yourPlans') }}</p>
          <h2>{{ activePlan ? t('training.otherPlans') : t('training.choosePlan') }}</h2>
        </header>
        <article v-for="plan in otherPlans" :key="plan.id">
          <RouterLink :to="`/plans/${plan.id}`"
            ><strong>{{ plan.name }}</strong
            ><small>{{
              t('training.routineCountSequence', { count: plan.routines.length })
            }}</small></RouterLink
          ><button type="button" @click="activate(plan.id)">
            {{ t('training.makeActive') }}
          </button>
        </article>
      </section>
    </template>
  </div>
</template>

<style scoped>
@reference '../../assets/base.css';

.plans-page {
  @apply space-y-4;
}
.page-intro {
  @apply grid grid-cols-[minmax(0,1fr)_auto] items-center gap-x-4 gap-y-2 px-1;
}
.eyebrow {
  @apply text-xs font-semibold uppercase tracking-wider text-slate-500;
}
h1 {
  @apply mt-1 text-2xl font-semibold tracking-tight text-slate-950;
}
h2 {
  @apply text-xl font-semibold tracking-tight text-slate-950;
}
.page-intro > a {
  @apply inline-flex min-h-11 shrink-0 items-center gap-2 rounded-xl bg-indigo-600 px-4 text-sm font-semibold text-white;
}
.page-intro svg {
  @apply size-5;
}
.page-intro > p {
  @apply col-span-2 max-w-none text-sm leading-6 text-slate-500;
}
.active-plan,
.other-plans,
.routine-list,
.paused-note,
.empty-plan-state,
.plan-loading {
  @apply rounded-2xl border border-slate-200 bg-white p-5 shadow-sm;
}
.plan-loading {
  @apply space-y-3;
}
.plan-loading span {
  @apply block h-4 animate-pulse rounded-full bg-slate-100;
}
.plan-loading span:first-child {
  @apply h-12 w-12 rounded-2xl;
}
.plan-loading span:nth-child(2) {
  @apply w-2/3;
}
.empty-plan-state {
  @apply p-6;
}
.empty-plan-icon {
  @apply mb-5 grid size-12 place-items-center rounded-2xl bg-indigo-100 text-indigo-700;
}
.empty-plan-icon svg {
  @apply size-6;
}
.empty-plan-state h2 {
  @apply mt-2 text-2xl;
}
.empty-plan-copy {
  @apply mt-2 text-sm leading-6 text-slate-600;
}
.plan-steps {
  @apply mt-6 divide-y divide-slate-100 border-y border-slate-100;
}
.plan-steps li {
  @apply flex items-center gap-3 py-4;
}
.plan-steps li > span {
  @apply grid size-9 shrink-0 place-items-center rounded-xl bg-indigo-50 text-sm font-semibold text-indigo-700;
}
.plan-steps li > span svg {
  @apply size-4;
}
.plan-steps strong,
.plan-steps small {
  @apply block;
}
.plan-steps strong {
  @apply text-sm font-semibold text-slate-900;
}
.plan-steps small {
  @apply mt-0.5 text-xs text-slate-500;
}
.active-plan-rule {
  @apply mt-5 text-xs leading-5 text-slate-500;
}
.first-plan-button {
  @apply mt-5 inline-flex min-h-12 w-full items-center justify-center gap-2 rounded-xl bg-indigo-600 px-4 text-sm font-semibold text-white hover:bg-indigo-700;
}
.first-plan-button svg {
  @apply size-5;
}
.active-plan > header {
  @apply flex items-center justify-between gap-3;
}
.active-plan > header span {
  @apply rounded-full bg-emerald-50 px-3 py-1 text-xs font-semibold text-emerald-700;
}
.active-plan > h2 {
  @apply mt-3;
}
.active-plan > p {
  @apply mt-1 text-sm text-slate-500;
}
.position-row {
  @apply mt-5 flex justify-between gap-3 text-sm text-slate-500;
}
.position-row strong {
  @apply text-slate-700;
}
.sequence {
  @apply mt-3 flex flex-wrap gap-2;
}
.sequence span {
  @apply grid size-9 place-items-center rounded-xl bg-slate-100 text-sm font-semibold text-slate-500;
}
.sequence span.done {
  @apply bg-emerald-50 text-emerald-700;
}
.sequence span.current {
  @apply bg-indigo-600 text-white;
}
.next-row {
  @apply mt-4 rounded-xl bg-indigo-50 p-4;
}
.next-row div {
  @apply grid gap-1;
}
.next-row small {
  @apply text-xs text-indigo-600;
}
.active-plan footer {
  @apply mt-4 flex gap-2 border-t border-slate-100 pt-4;
}
.active-plan footer a,
.active-plan footer button {
  @apply min-h-10 rounded-xl px-4 text-sm font-semibold;
}
.active-plan footer a {
  @apply inline-flex items-center bg-indigo-600 text-white;
}
.active-plan footer button {
  @apply border border-slate-200 text-slate-600;
}
.paused-note p {
  @apply mt-1 text-sm text-slate-500;
}
.other-plans > header {
  @apply mb-2;
}
.other-plans article {
  @apply flex min-h-16 items-center justify-between gap-3 border-t border-slate-100;
}
.other-plans article a {
  @apply min-w-0;
}
.other-plans article strong,
.other-plans article small {
  @apply block truncate;
}
.other-plans article small {
  @apply mt-1 text-xs text-slate-500;
}
.other-plans article button {
  @apply shrink-0 text-sm font-semibold text-indigo-600;
}
.routine-list strong,
.routine-empty h2 {
  @apply text-lg font-semibold text-slate-900;
}
.routine-empty p {
  @apply mt-1;
}
</style>

// web/src/ui/plans/PlansView.tsx
import { ArrowPathIcon, CheckIcon, PlusIcon } from '@heroicons/react/24/outline'
import { useEffect, useState } from 'react'
import { useTranslation } from 'react-i18next'
import { Link } from 'react-router-dom'

import { useConfirmationStore } from '@/stores/confirmation'
import { useDashboardStore } from '@/stores/dashboard'
import { selectActivePlan, usePlanStore } from '@/stores/plans'
import { cn } from '@/ui/cn'
import { AppButton } from '@/ui/components/AppButton'
import { AppSkeleton } from '@/ui/components/AppSkeleton'
import { TrainingTabs } from '@/ui/features/TrainingTabs'
import styles from './PlansView.module.css'

/** Every plan: which one is running, where it is, and what else is available. */
export const PlansView = () => {
  const { t } = useTranslation()

  const plans = usePlanStore((state) => state.plans)
  const activePlan = usePlanStore(selectActivePlan)

  const [loaded, setLoaded] = useState(false)

  useEffect(() => {
    const load = async () => {
      await usePlanStore.getState().load()
      setLoaded(true)
    }
    void load()
  }, [])

  const otherPlans = plans.filter((plan) => !plan.active)
  const nextRoutine = activePlan?.routines[activePlan.currentPosition]

  // Only one plan runs at a time, so activating another one ends the first.
  const activate = async (id: string) => {
    if (activePlan) {
      const confirmed = await useConfirmationStore.getState().confirm({
        body: t('training.activateConfirmBody'),
        confirmLabel: t('training.makeActive'),
        title: t('training.activateConfirmTitle'),
      })
      if (!confirmed) return
    }

    if (await usePlanStore.getState().activate(id)) await useDashboardStore.getState().load()
  }

  const pause = async () => {
    const confirmed = await useConfirmationStore.getState().confirm({
      body: t('training.pauseConfirmBody'),
      confirmLabel: t('training.pause'),
      title: t('training.pauseConfirmTitle'),
    })
    if (!confirmed) return

    if (await usePlanStore.getState().pause()) await useDashboardStore.getState().load()
  }

  return (
    <div className={styles.plansPage}>
      <header className={styles.pageIntro}>
        <div>
          <h1>{t('training.heading')}</h1>
        </div>
        {plans.length > 0 && (
          <Link to="/plans/create">
            <PlusIcon aria-hidden="true" /> {t('training.newPlan')}
          </Link>
        )}
        <p>{t('training.plansDescription')}</p>
      </header>

      <TrainingTabs />

      {!loaded ? (
        <AppSkeleton />
      ) : plans.length === 0 ? (
        // A plan is an unfamiliar idea, so the empty state teaches it rather
        // than just offering a button.
        <section className={styles.emptyPlanState}>
          <span className={styles.emptyPlanIcon}>
            <ArrowPathIcon aria-hidden="true" />
          </span>
          <p className={styles.eyebrow}>{t('training.howPlansWork')}</p>
          <h2>{t('training.repeatingTitle')}</h2>
          <p className={styles.emptyPlanCopy}>{t('training.repeatingBody')}</p>

          <ol className={styles.planSteps}>
            <li>
              <span>1</span>
              <div>
                <strong>{t('training.chooseRoutines')}</strong>
                <small>{t('training.chooseRoutinesBody')}</small>
              </div>
            </li>
            <li>
              <span>2</span>
              <div>
                <strong>{t('training.activatePlan')}</strong>
                <small>{t('training.activatePlanBody')}</small>
              </div>
            </li>
            <li>
              <span>
                <CheckIcon aria-hidden="true" />
              </span>
              <div>
                <strong>{t('training.keepTraining')}</strong>
                <small>{t('training.keepTrainingBody')}</small>
              </div>
            </li>
          </ol>

          <p className={styles.activePlanRule}>{t('training.oneActive')}</p>
          <Link to="/plans/create" className={styles.firstPlanButton}>
            <PlusIcon aria-hidden="true" /> {t('training.createFirstPlan')}
          </Link>
        </section>
      ) : (
        <>
          {activePlan ? (
            <section className={styles.activePlan}>
              <header>
                <p className={styles.eyebrow}>{t('training.activePlan')}</p>
                <span>{t('training.active')}</span>
              </header>
              <h2>{activePlan.name}</h2>
              <p>{t('training.routineCountRepeats', { count: activePlan.routines.length })}</p>

              <div className={styles.positionRow}>
                <span>{t('training.currentPosition')}</span>
                <strong>
                  {t('training.routinePosition', {
                    current: activePlan.currentPosition + 1,
                    total: activePlan.routines.length,
                  })}
                </strong>
              </div>

              <div className={styles.sequence} aria-label={t('training.planPositionAria')}>
                {activePlan.routines.map((routine, index) => (
                  <span
                    key={routine.id}
                    className={cn(
                      index === activePlan.currentPosition && styles.current,
                      index < activePlan.currentPosition && styles.done,
                    )}
                  >
                    {index + 1}
                  </span>
                ))}
              </div>

              {nextRoutine && (
                <div className={styles.nextRow}>
                  <div>
                    <small>{t('home.upNext')}</small>
                    <strong>{nextRoutine.name}</strong>
                    <small>
                      {t('home.exerciseCount', { count: nextRoutine.exercises.length })}
                    </small>
                  </div>
                </div>
              )}

              <footer>
                <AppButton
                  type="link"
                  colour="primary"
                  size="sm"
                  width="auto"
                  to={`/plans/${activePlan.id}`}
                >
                  {t('training.viewPlan')}
                </AppButton>
                <AppButton
                  type="button"
                  colour="secondary"
                  size="sm"
                  width="auto"
                  onClick={() => void pause()}
                >
                  {t('training.pause')}
                </AppButton>
              </footer>
            </section>
          ) : (
            <section className={styles.pausedNote}>
              <h2>{t('training.noActivePlan')}</h2>
              <p>{t('training.noActivePlanBody')}</p>
            </section>
          )}

          {otherPlans.length > 0 && (
            <section className={styles.otherPlans}>
              <header>
                <p className={styles.eyebrow}>{t('training.yourPlans')}</p>
                <h2>{activePlan ? t('training.otherPlans') : t('training.choosePlan')}</h2>
              </header>
              {otherPlans.map((plan) => (
                <article key={plan.id}>
                  <Link to={`/plans/${plan.id}`}>
                    <strong>{plan.name}</strong>
                    <small>
                      {t('training.routineCountSequence', { count: plan.routines.length })}
                    </small>
                  </Link>
                  <AppButton
                    type="button"
                    colour="ghost"
                    size="sm"
                    width="auto"
                    className={styles.makeActive}
                    onClick={() => void activate(plan.id)}
                  >
                    {t('training.makeActive')}
                  </AppButton>
                </article>
              ))}
            </section>
          )}
        </>
      )}
    </div>
  )
}
