// web/src/ui/exercises/ExerciseMeasurementSettings.tsx
import { useTranslation } from 'react-i18next'

import { ExerciseMetric } from '@/proto/api/v1/shared_pb'
import { usePreferencesStore } from '@/stores/preferences'
import { cn } from '@/ui/cn'
import { AppSegmented } from '@/ui/components/AppSegmented'
import { distanceUnitLabel } from '@/utils/distanceUnits'
import { weightUnitLabel } from '@/utils/weightUnits'
import styles from './ExerciseMeasurementSettings.module.css'

/** The rest length a switched-on timer starts at. */
export const defaultRestSeconds = 90

// Every 30 seconds up to five minutes, so any common rest length is one tap.
const restPresets = Array.from({ length: 10 }, (_, index) => (index + 1) * 30)

const formatRest = (seconds: number) =>
  `${Math.floor(seconds / 60)}:${String(seconds % 60).padStart(2, '0')}`

const presets = [
  {
    labelKey: 'exercise.measurements.presetWeightReps',
    values: [ExerciseMetric.WEIGHT, ExerciseMetric.REPS],
  },
  {
    labelKey: 'exercise.measurements.presetDistanceTime',
    values: [ExerciseMetric.DISTANCE, ExerciseMetric.TIME],
  },
  { labelKey: 'exercise.measurements.presetRepsOnly', values: [ExerciseMetric.REPS] },
  { labelKey: 'exercise.measurements.presetTimed', values: [ExerciseMetric.TIME] },
]

interface Props {
  metrics: ExerciseMetric[]
  onMetricsChange: (metrics: ExerciseMetric[]) => void
  restSeconds: number
  onRestSecondsChange: (seconds: number) => void
}

/** What an exercise measures, and how long its rest runs for. */
export const ExerciseMeasurementSettings = ({
  metrics,
  onMetricsChange,
  restSeconds,
  onRestSecondsChange,
}: Props) => {
  const { t } = useTranslation()
  const weightUnit = usePreferencesStore((state) => state.weightUnit)
  const distanceUnit = usePreferencesStore((state) => state.distanceUnit)

  // The unit hints reflect the signed-in user's preferences so the card shows
  // what a set of this exercise will actually be logged in.
  const measurements = [
    { value: ExerciseMetric.WEIGHT, label: t('common.weight'), unit: weightUnitLabel(weightUnit) },
    {
      value: ExerciseMetric.REPS,
      label: t('common.reps'),
      unit: t('exercise.measurements.unitCount'),
    },
    {
      value: ExerciseMetric.DISTANCE,
      label: t('common.distance'),
      unit: distanceUnitLabel(distanceUnit),
    },
    {
      value: ExerciseMetric.TIME,
      label: t('common.time'),
      unit: t('exercise.measurements.unitMinSec'),
    },
  ]

  const isPreset = (values: ExerciseMetric[]) =>
    values.length === metrics.length && values.every((value) => metrics.includes(value))

  // An exercise that measures nothing cannot log a set, so the last one stays.
  const toggleMetric = (metric: ExerciseMetric) => {
    if (!metrics.includes(metric)) {
      onMetricsChange([...metrics, metric])
      return
    }
    if (metrics.length === 1) return
    onMetricsChange(metrics.filter((value) => value !== metric))
  }

  const restEnabled = restSeconds > 0

  return (
    <section className={styles.settings}>
      <div>
        <h3>{t('exercise.measurements.heading')}</h3>
        <p>{t('exercise.measurements.help')}</p>
      </div>

      <AppSegmented
        label={t('exercise.measurements.presetsAria')}
        options={presets.map((preset) => ({ label: t(preset.labelKey), value: preset }))}
        value={presets.find((preset) => isPreset(preset.values))}
        onChange={(preset) => preset && onMetricsChange([...preset.values])}
      />

      <div
        className={styles.measurementGrid}
        role="group"
        aria-label={t('exercise.measurements.heading')}
      >
        {measurements.map((measurement) => (
          <button
            key={measurement.value}
            type="button"
            className={cn(
              styles.measurement,
              metrics.includes(measurement.value) && styles.selected,
            )}
            aria-pressed={metrics.includes(measurement.value)}
            onClick={() => toggleMetric(measurement.value)}
          >
            <span className={styles.check} aria-hidden="true">
              {metrics.includes(measurement.value) ? '✓' : '+'}
            </span>
            <span>
              <strong>{measurement.label}</strong>
              <small>{measurement.unit}</small>
            </span>
          </button>
        ))}
      </div>

      <div className={styles.restSetting}>
        <div>
          <strong>{t('exercise.restTimer')}</strong>
          <small>{t('exercise.measurements.restHelp')}</small>
        </div>
        <button
          type="button"
          role="switch"
          className={styles.switch}
          aria-checked={restEnabled}
          aria-label={t('exercise.restTimer')}
          onClick={() => onRestSecondsChange(restEnabled ? 0 : defaultRestSeconds)}
        >
          <span className={styles.knob} />
        </button>
      </div>

      {restEnabled && (
        <AppSegmented
          label={t('exercise.restTimer')}
          options={restPresets.map((seconds) => ({ label: formatRest(seconds), value: seconds }))}
          value={restSeconds}
          onChange={onRestSecondsChange}
        />
      )}
    </section>
  )
}

// web/src/ui/exercises/ExerciseMeasurementSettings.vue
<script setup lang="ts">
import { computed } from 'vue'
import { useI18n } from 'vue-i18n'
import { ExerciseMetric } from '@/proto/api/v1/shared_pb'
import { usePreferencesStore } from '@/stores/preferences'
import { weightUnitLabel } from '@/utils/weightUnits'
import { distanceUnitLabel } from '@/utils/distanceUnits'

const { t } = useI18n()
const preferencesStore = usePreferencesStore()

const metrics = defineModel<ExerciseMetric[]>('metrics', { required: true })
const restSeconds = defineModel<number>('restSeconds', { required: true })

// The unit hints reflect the signed-in user's preferences so the card shows
// what a set of this exercise will actually be logged in.
const measurements = computed(() => [
  {
    value: ExerciseMetric.WEIGHT,
    label: t('common.weight'),
    unit: weightUnitLabel(preferencesStore.weightUnit),
  },
  {
    value: ExerciseMetric.REPS,
    label: t('common.reps'),
    unit: t('exercise.measurements.unitCount'),
  },
  {
    value: ExerciseMetric.DISTANCE,
    label: t('common.distance'),
    unit: distanceUnitLabel(preferencesStore.distanceUnit),
  },
  {
    value: ExerciseMetric.TIME,
    label: t('common.time'),
    unit: t('exercise.measurements.unitMinSec'),
  },
])

const presets = computed(() => [
  {
    label: t('exercise.measurements.presetWeightReps'),
    values: [ExerciseMetric.WEIGHT, ExerciseMetric.REPS],
  },
  {
    label: t('exercise.measurements.presetDistanceTime'),
    values: [ExerciseMetric.DISTANCE, ExerciseMetric.TIME],
  },
  { label: t('exercise.measurements.presetRepsOnly'), values: [ExerciseMetric.REPS] },
  { label: t('exercise.measurements.presetTimed'), values: [ExerciseMetric.TIME] },
])

const restEnabled = computed({
  get: () => restSeconds.value > 0,
  set: (enabled: boolean) => (restSeconds.value = enabled ? 90 : 0),
})

// Every 30 seconds up to five minutes, so any common rest length is one tap.
const restPresets = Array.from({ length: 10 }, (_, index) => (index + 1) * 30)
const formatRest = (seconds: number) =>
  `${Math.floor(seconds / 60)}:${String(seconds % 60).padStart(2, '0')}`

function sameMetrics(values: ExerciseMetric[]) {
  return (
    values.length === metrics.value.length && values.every((value) => metrics.value.includes(value))
  )
}

function toggleMetric(metric: ExerciseMetric) {
  if (metrics.value.includes(metric)) {
    if (metrics.value.length === 1) return
    metrics.value = metrics.value.filter((value) => value !== metric)
    return
  }
  metrics.value = [...metrics.value, metric]
}
</script>

<template>
  <section class="measurement-settings">
    <div>
      <h3>{{ t('exercise.measurements.heading') }}</h3>
      <p>{{ t('exercise.measurements.help') }}</p>
    </div>

    <div class="presets segmented" :aria-label="t('exercise.measurements.presetsAria')">
      <button
        v-for="preset in presets"
        :key="preset.label"
        type="button"
        :class="{ 'is-selected': sameMetrics(preset.values) }"
        :aria-pressed="sameMetrics(preset.values)"
        @click="metrics = [...preset.values]"
      >
        {{ preset.label }}
      </button>
    </div>

    <div class="measurement-grid">
      <button
        v-for="measurement in measurements"
        :key="measurement.value"
        type="button"
        class="measurement"
        :class="{ selected: metrics.includes(measurement.value) }"
        :aria-pressed="metrics.includes(measurement.value)"
        @click="toggleMetric(measurement.value)"
      >
        <span class="check">{{ metrics.includes(measurement.value) ? '✓' : '+' }}</span>
        <span>
          <strong>{{ measurement.label }}</strong>
          <small>{{ measurement.unit }}</small>
        </span>
      </button>
    </div>

    <div class="rest-setting">
      <div>
        <strong>{{ t('exercise.restTimer') }}</strong>
        <small>{{ t('exercise.measurements.restHelp') }}</small>
      </div>
      <button
        type="button"
        role="switch"
        class="switch"
        :aria-checked="restEnabled"
        :aria-label="t('exercise.restTimer')"
        @click="restEnabled = !restEnabled"
      >
        <span class="knob"></span>
      </button>
    </div>

    <div v-if="restEnabled" class="rest-options">
      <button
        v-for="seconds in restPresets"
        :key="seconds"
        type="button"
        :aria-pressed="restSeconds === seconds"
        :class="{ selected: restSeconds === seconds }"
        @click="restSeconds = seconds"
      >
        {{ formatRest(seconds) }}
      </button>
    </div>
  </section>
</template>

<style scoped>
@reference '../../assets/base.css';

.measurement-settings {
  @apply space-y-5 rounded-card border border-border bg-white p-5 shadow-card;
}
h3 {
  @apply text-title font-bold text-text;
}
p,
small {
  @apply block text-sm text-text-subtle;
}
.rest-options {
  @apply flex flex-wrap gap-2;
}
.rest-options button {
  @apply inline-flex min-h-(--size-control-sm) items-center rounded-control border border-border bg-white px-4 text-sm font-semibold text-text-muted;
}
.rest-options button.selected {
  @apply border-surface-inverse bg-surface-inverse text-white;
}
.measurement-grid {
  @apply grid grid-cols-2 gap-3;
}
.measurement {
  @apply flex min-h-(--size-control-sm) items-center gap-3 rounded-card border border-border p-4 text-left;
}
.measurement.selected {
  @apply border-surface-inverse bg-surface-sunken;
}
.measurement strong {
  @apply block text-base text-text;
}
.check {
  @apply flex h-8 w-8 shrink-0 items-center justify-center rounded-full bg-ink-tint font-bold;
}
.measurement.selected .check {
  @apply bg-surface-inverse text-white;
}
.rest-setting {
  @apply flex items-center justify-between border-t border-border pt-5;
}
.rest-setting strong {
  @apply block text-base text-text;
}
/* A real track-and-knob switch: the old pill read as a button. The track is
   drawn rather than being the button itself, so the control can be the full
   tap-target height to a thumb while still reading as a 32px switch. */
.switch {
  @apply relative inline-flex min-h-(--size-control-sm) w-14 shrink-0 cursor-pointer items-center;
}
.switch::before {
  @apply absolute inset-x-0 top-1/2 h-8 -translate-y-1/2 rounded-full bg-ink-tint transition-colors content-[''];
}
.switch[aria-checked='true']::before {
  @apply bg-surface-inverse;
}
.knob {
  @apply absolute left-1 top-1/2 size-6 -translate-y-1/2 rounded-full bg-white shadow-card transition-transform;
}
.switch[aria-checked='true'] .knob {
  @apply translate-x-6;
}
</style>
