// web/src/ui/components/AppConfirmDialog.tsx
import { useEffect } from 'react'
import { useTranslation } from 'react-i18next'

import { useConfirmationStore } from '@/stores/confirmation'
import { AppSheet, SheetAction } from '@/ui/components/AppSheet'
import blurActiveElement from '@/utils/blurActiveElement'

/**
 * The app-styled replacement for `window.confirm`.
 *
 * One instance renders whatever `useConfirmationStore.confirm()` was last
 * asked for, so any code can ask a question without owning a dialog.
 */
export const AppConfirmDialog = () => {
  const { t } = useTranslation()
  const confirmation = useConfirmationStore((state) => state.confirmation)

  // The sheet slides over whatever had focus, and a still-focused field behind
  // it keeps the on-screen keyboard up.
  useEffect(() => {
    if (confirmation) blurActiveElement()
  }, [confirmation])

  if (!confirmation) return null

  const { accept, dismiss } = useConfirmationStore.getState()

  return (
    <AppSheet
      title={confirmation.title}
      body={confirmation.body}
      onClose={dismiss}
      actions={
        <>
          <SheetAction tone={confirmation.destructive ? 'danger' : 'primary'} onClick={accept}>
            {confirmation.confirmLabel}
          </SheetAction>
          <SheetAction tone="tertiary" onClick={dismiss}>
            {confirmation.cancelLabel ?? t('common.cancel')}
          </SheetAction>
        </>
      }
    />
  )
}

// web/src/ui/components/AppConfirmDialog.vue
<script setup lang="ts">
import { watch } from 'vue'
import { useI18n } from 'vue-i18n'

import { useConfirmationStore } from '@/stores/confirmation'
import AppSheet from '@/ui/components/AppSheet.vue'
import blurActiveElement from '@/utils/blurActiveElement'

const { t } = useI18n()
const confirmationStore = useConfirmationStore()

watch(
  () => confirmationStore.confirmation,
  (confirmation) => {
    if (confirmation) blurActiveElement()
  },
)
</script>

<template>
  <AppSheet
    v-if="confirmationStore.confirmation"
    :title="confirmationStore.confirmation.title"
    :body="confirmationStore.confirmation.body"
    @close="confirmationStore.dismiss"
  >
    <template #actions>
      <button
        type="button"
        class="dialog-confirm"
        :class="confirmationStore.confirmation.destructive ? 'danger destructive' : 'primary'"
        @click="confirmationStore.accept"
      >
        {{ confirmationStore.confirmation.confirmLabel }}
      </button>
      <button type="button" class="dialog-cancel tertiary" @click="confirmationStore.dismiss">
        {{ confirmationStore.confirmation.cancelLabel ?? t('common.cancel') }}
      </button>
    </template>
  </AppSheet>
</template>
