// web/src/ui/components/AppEmptyState.vue
<script setup lang="ts">
// Six dashed-border variants at three padding values and two backgrounds said
// the same thing six ways, and only one of them offered a way out.
//
// This is the one place in the design foundation where a component earns its
// keep over a CSS class, because the rule being enforced is editorial: always
// offer a next step. `action` is required — not required to exist, required to
// be decided. A screen with genuinely nowhere to go has to write action="none"
// in its own markup, where a reviewer will see the choice being made. A class
// cannot make anyone choose.
type Action = { label: string; to?: string }

defineProps<{
  action: Action | 'none'
  body?: string
  title: string
}>()

const emit = defineEmits<{ action: [] }>()
</script>

<template>
  <div class="empty-state">
    <span v-if="$slots.icon" class="empty-icon"><slot name="icon" /></span>
    <h2>{{ title }}</h2>
    <p v-if="body">{{ body }}</p>
    <RouterLink v-if="action !== 'none' && action.to" :to="action.to" class="empty-action">
      <slot name="action-icon" />{{ action.label }}
    </RouterLink>
    <button
      v-else-if="action !== 'none'"
      type="button"
      class="empty-action"
      @click="emit('action')"
    >
      <slot name="action-icon" />{{ action.label }}
    </button>
  </div>
</template>

<style scoped>
@reference '../../assets/base.css';

.empty-state {
  @apply grid justify-items-start gap-3 rounded-card border border-dashed border-border-strong bg-surface p-6;
}
.empty-icon {
  @apply grid size-11 place-items-center rounded-control bg-surface-sunken text-text-subtle;
}
.empty-icon :deep(svg) {
  @apply size-5;
}
.empty-state h2 {
  @apply text-body-lg font-semibold text-text;
}
.empty-state p {
  @apply text-sm leading-6 text-text-muted;
}
.empty-action {
  @apply mt-1 inline-flex min-h-(--size-control) items-center gap-2 rounded-control bg-ink px-4 text-sm font-semibold text-white transition hover:brightness-125;
}
.empty-action :deep(svg) {
  @apply size-5;
}
</style>

// web/src/ui/components/AppEmptyState.tsx
import type { ReactNode } from 'react'

import { Link } from 'react-router-dom'

import styles from './AppEmptyState.module.css'

// Six dashed-border variants at three padding values and two backgrounds said
// the same thing six ways, and only one of them offered a way out.
//
// This is the one place in the design foundation where a component earns its
// keep over a CSS class, because the rule being enforced is editorial: always
// offer a next step. `action` is required — not required to exist, required to
// be decided. A screen with genuinely nowhere to go has to write action="none"
// in its own markup, where a reviewer will see the choice being made. A class
// cannot make anyone choose.
export type EmptyStateAction = { label: string; to?: string }

interface Props {
  action: EmptyStateAction | 'none'
  title: string
  body?: string
  icon?: ReactNode
  actionIcon?: ReactNode
  onAction?: () => void
}

export const AppEmptyState = ({ action, title, body, icon, actionIcon, onAction }: Props) => (
  <div className={styles.emptyState}>
    {icon && <span className={styles.emptyIcon}>{icon}</span>}
    <h2>{title}</h2>
    {body && <p>{body}</p>}

    {action !== 'none' &&
      (action.to ? (
        <Link to={action.to} className={styles.emptyAction}>
          {actionIcon}
          {action.label}
        </Link>
      ) : (
        <button type="button" className={styles.emptyAction} onClick={onAction}>
          {actionIcon}
          {action.label}
        </button>
      ))}
  </div>
)
