// web/src/ui/components/AppSkeleton.tsx
import { useTranslation } from 'react-i18next'

import { cn } from '@/ui/cn'

interface Props {
  lines?: number
  className?: string
}

// The shared pulsating placeholder for anything that fetches from the API.
// Screens drop it in behind their loading flag; the .loading-card class also
// doubles as the settle sentinel for the screenshot harness.
export const AppSkeleton = ({ lines = 3, className }: Props) => {
  const { t } = useTranslation()

  return (
    <div className={cn('loading-card', className)} aria-busy="true" aria-live="polite">
      <span className="sr-only">{t('common.loading')}</span>
      {Array.from({ length: lines }, (_, index) => (
        <div
          key={index}
          className={cn('loading-line', index === lines - 1 && 'w-full')}
          aria-hidden="true"
        />
      ))}
    </div>
  )
}

// web/src/ui/components/AppSkeleton.vue
<script setup lang="ts">
import { useI18n } from 'vue-i18n'

// The shared pulsating placeholder for anything that fetches from the API.
// Screens drop it in behind their loading flag; the .loading-card class also
// doubles as the settle sentinel for the screenshot harness.
withDefaults(defineProps<{ lines?: number }>(), { lines: 3 })

const { t } = useI18n()
</script>

<template>
  <div class="loading-card" aria-busy="true" aria-live="polite">
    <span class="sr-only">{{ t('common.loading') }}</span>
    <div
      v-for="line in lines"
      :key="line"
      class="loading-line"
      :class="{ 'w-full': line === lines }"
      aria-hidden="true"
    ></div>
  </div>
</template>
