// web-next/src/ui/components/AppTextarea.tsx
export default function AppTextarea({ placeholder, rows }: { placeholder: string; rows: number }) {
  return (
    <textarea
      className="mb-1 w-full rounded-control border border-ink-border shadow-card focus:border-ink-muted focus:ring-ink-muted sm:text-sm"
      placeholder={placeholder}
      rows={rows}
    />
  )
}

// web/src/ui/components/AppTextarea.vue
<script setup lang="ts">
const props = defineProps<{
  placeholder: string
  rows: number
}>()
</script>

<template>
  <textarea
    class="w-full border border-ink-border rounded-control shadow-card focus:ring-ink-muted focus:border-ink-muted sm:text-sm mb-1"
    :placeholder="props.placeholder"
    :rows="props.rows"
  />
</template>

<style scoped></style>
