// web/src/ui/components/DropdownButton.vue
<script setup lang="ts">
import type { DropdownItem } from '@/types/dropdown'
import { EllipsisHorizontalIcon } from '@heroicons/vue/24/outline'
import { Menu, MenuButton, MenuItem, MenuItems } from '@headlessui/vue'

defineProps<{ items: DropdownItem[] }>()
</script>

<template>
  <Menu as="div" class="relative inline-block text-left">
    <MenuButton class="menu-trigger" aria-label="Workout actions">
      <EllipsisHorizontalIcon />
    </MenuButton>
    <transition
      enter-active-class="transition duration-100 ease-out"
      enter-from-class="scale-95 opacity-0"
      enter-to-class="scale-100 opacity-100"
      leave-active-class="transition duration-75 ease-in"
      leave-from-class="scale-100 opacity-100"
      leave-to-class="scale-95 opacity-0"
    >
      <MenuItems class="menu-items">
        <MenuItem v-for="item in items" :key="item.title" v-slot="{ active }">
          <RouterLink v-if="item.href" :to="item.href" class="menu-item" :class="{ active }">
            {{ item.title }}
          </RouterLink>
          <button v-else type="button" class="menu-item danger" :class="{ active }" @click="item.func">
            {{ item.title }}
          </button>
        </MenuItem>
      </MenuItems>
    </transition>
  </Menu>
</template>

<style scoped>
.menu-trigger { @apply grid size-10 place-items-center rounded-xl border border-slate-200 bg-white text-slate-500 transition hover:border-indigo-200 hover:bg-indigo-50 hover:text-indigo-700; }
.menu-trigger svg { @apply size-5; }
.menu-items { @apply absolute right-0 z-50 mt-2 w-48 origin-top-right space-y-1 rounded-xl border border-slate-200 bg-white p-1.5 shadow-xl focus:outline-none; }
.menu-item { @apply block w-full rounded-lg px-3 py-2.5 text-left text-sm font-medium text-slate-700; }
.menu-item.active { @apply bg-slate-50; }
.menu-item.danger { @apply text-red-600; }
.menu-item.danger.active { @apply bg-red-50; }
</style>

// web/src/ui/components/DropdownButton.tsx
import type { DropdownItem } from '@/types/dropdown'

import { Menu, MenuButton, MenuItem, MenuItems, Transition } from '@headlessui/react'
import { EllipsisHorizontalIcon } from '@heroicons/react/24/outline'
import { useTranslation } from 'react-i18next'
import { Link } from 'react-router-dom'

import { cn } from '@/ui/cn'
import styles from './DropdownButton.module.css'

interface Props {
  items: DropdownItem[]
  label?: string
  className?: string
}

export const DropdownButton = ({ items, label, className }: Props) => {
  const { t } = useTranslation()

  return (
    <Menu as="div" className="relative inline-block text-left">
      <MenuButton
        className={cn(styles.menuTrigger, className)}
        aria-label={label ?? t('workout.card.actionsAria')}
      >
        <EllipsisHorizontalIcon aria-hidden="true" />
      </MenuButton>

      <Transition
        enter={styles.enter}
        enterFrom={styles.enterFrom}
        enterTo={styles.enterTo}
        leave={styles.leave}
        leaveFrom={styles.enterTo}
        leaveTo={styles.enterFrom}
      >
        <MenuItems className={styles.menuItems}>
          {items.map((item) => (
            <MenuItem key={item.title}>
              {({ focus }) =>
                item.href ? (
                  <Link to={item.href} className={cn(styles.menuItem, focus && styles.active)}>
                    {item.title}
                  </Link>
                ) : (
                  <button
                    type="button"
                    className={cn(
                      styles.menuItem,
                      item.destructive && styles.danger,
                      focus && styles.active,
                    )}
                    onClick={() => void item.func?.()}
                  >
                    {item.title}
                  </button>
                )
              }
            </MenuItem>
          ))}
        </MenuItems>
      </Transition>
    </Menu>
  )
}
