// web-next/src/ui/components/DropdownButton.tsx
import { EllipsisHorizontalIcon } from '@heroicons/react/24/outline'
import { Menu, MenuButton, MenuItem, MenuItems } from '@headlessui/react'
import { useTranslation } from 'react-i18next'
import { Link } from 'react-router-dom'
import type { DropdownItem } from '@/types/dropdown'

export default function DropdownButton({
  items,
  label,
}: {
  items: DropdownItem[]
  label?: string
}) {
  const { t } = useTranslation()
  const menuLabel = label ?? t('workout.card.actionsAria')

  return (
    <Menu as="div" className="relative inline-block text-left">
      <MenuButton
        aria-label={menuLabel}
        className="grid size-11 place-items-center rounded-control border border-border bg-white text-text-subtle transition hover:border-ink-border hover:bg-ink-surface hover:text-ink-strong [&>svg]:size-5"
      >
        <EllipsisHorizontalIcon />
      </MenuButton>
      <MenuItems
        transition
        className="absolute right-0 z-50 mt-2 w-48 origin-top-right scale-100 space-y-1 rounded-control border border-border bg-white p-1.5 opacity-100 shadow-overlay transition duration-100 ease-out focus:outline-none data-closed:scale-95 data-closed:opacity-0 data-leave:duration-75 data-leave:ease-in"
      >
        {items.map((item) =>
          item.href ? (
            <MenuItem key={item.title}>
              <Link
                to={item.href}
                className="flex min-h-(--size-control-sm) w-full items-center rounded-lg px-3 text-left text-sm font-medium text-text-muted data-focus:bg-ink-surface"
              >
                {item.title}
              </Link>
            </MenuItem>
          ) : (
            <MenuItem key={item.title}>
              <button
                type="button"
                onClick={item.func}
                className="flex min-h-(--size-control-sm) w-full items-center rounded-lg px-3 text-left text-sm font-medium text-danger data-focus:bg-danger-surface"
              >
                {item.title}
              </button>
            </MenuItem>
          ),
        )}
      </MenuItems>
    </Menu>
  )
}

// web/src/ui/components/DropdownButton.vue
<script setup lang="ts">
import type { DropdownItem } from '@/types/dropdown'
import { EllipsisHorizontalIcon } from '@heroicons/vue/24/outline'
import { Menu, MenuButton, MenuItem, MenuItems } from '@headlessui/vue'

withDefaults(defineProps<{ items: DropdownItem[]; label?: string }>(), {
  label: 'Workout actions',
})
</script>

<template>
  <Menu as="div" class="relative inline-block text-left">
    <MenuButton class="menu-trigger" :aria-label="label">
      <EllipsisHorizontalIcon />
    </MenuButton>
    <transition
      enter-active-class="transition duration-100 ease-out"
      enter-from-class="scale-95 opacity-0"
      enter-to-class="scale-100 opacity-100"
      leave-active-class="transition duration-75 ease-in"
      leave-from-class="scale-100 opacity-100"
      leave-to-class="scale-95 opacity-0"
    >
      <MenuItems class="menu-items">
        <MenuItem v-for="item in items" :key="item.title" v-slot="{ active }">
          <RouterLink v-if="item.href" :to="item.href" class="menu-item" :class="{ active }">
            {{ item.title }}
          </RouterLink>
          <button
            v-else
            type="button"
            class="menu-item danger"
            :class="{ active }"
            @click="item.func"
          >
            {{ item.title }}
          </button>
        </MenuItem>
      </MenuItems>
    </transition>
  </Menu>
</template>

<style scoped>
@reference '../../assets/base.css';

.menu-trigger {
  @apply grid size-11 place-items-center rounded-xl border border-slate-200 bg-white text-slate-500 transition hover:border-ink-border hover:bg-ink-surface hover:text-ink-strong;
}
.menu-trigger svg {
  @apply size-5;
}
.menu-items {
  @apply absolute right-0 z-50 mt-2 w-48 origin-top-right space-y-1 rounded-xl border border-slate-200 bg-white p-1.5 shadow-xl focus:outline-none;
}
.menu-item {
  @apply flex min-h-(--size-control-sm) w-full items-center rounded-lg px-3 text-left text-sm font-medium text-slate-700;
}
.menu-item.active {
  @apply bg-slate-50;
}
.menu-item.danger {
  @apply text-red-600;
}
.menu-item.danger.active {
  @apply bg-red-50;
}
</style>
