// web/src/ui/features/NotificationWorkoutComment.tsx
import type { User } from '@/proto/api/v1/shared_pb'
import type { Workout } from '@/proto/api/v1/workout_service_pb'

import { ChatBubbleLeftRightIcon } from '@heroicons/react/24/outline'
import { Link } from 'react-router-dom'

import { RichMessage } from '@/i18n/RichMessage'
import { useAuthStore } from '@/stores/auth'
import { formatUnixTimestamp } from '@/utils/datetime'
import { handle } from '@/utils/names'

interface Props {
  actor?: User
  timestamp: bigint
  workout?: Workout
}

/** A "someone commented" row, linking to the workout they commented on. */
export const NotificationWorkoutComment = ({ actor, timestamp, workout }: Props) => {
  const userId = useAuthStore((state) => state.userId)

  // The owner changes the sentence, not just a word ("din"/"sin" bind to the
  // noun in Swedish), so each ownership case is a complete message.
  const messageKey =
    userId === workout?.user?.id
      ? 'notifications.commentedOnYourWorkout'
      : actor?.id === workout?.user?.id
        ? 'notifications.commentedOnTheirWorkout'
        : 'notifications.commentedOnUsersWorkout'

  return (
    <Link to={`/workouts/${workout?.id}`} className="flex w-full items-center gap-x-3">
      <ChatBubbleLeftRightIcon className="size-7" aria-hidden="true" />
      <div className="w-full font-normal">
        <div>
          <RichMessage
            i18nKey={messageKey}
            values={{ owner: handle(workout?.user?.username) }}
            nodes={{
              name: <span className="font-semibold">{handle(actor?.username)}</span>,
              workout: <span className="font-semibold">{workout?.name}</span>,
            }}
          />
        </div>
        <p className="text-sm text-text-subtle">{formatUnixTimestamp(timestamp)}</p>
      </div>
    </Link>
  )
}

// web/src/ui/components/NotificationWorkoutComment.vue
<script setup lang="ts">
import type { User } from '@/proto/api/v1/shared_pb.ts'
import type { Workout } from '@/proto/api/v1/workout_service_pb'

import { computed } from 'vue'
import { useAuthStore } from '@/stores/auth.ts'
import { formatUnixToRelativeDateTime } from '@/utils/datetime.ts'
import { ChatBubbleLeftRightIcon } from '@heroicons/vue/24/outline'

const authStore = useAuthStore()

const props = defineProps<{
  actor?: User
  timestamp: bigint
  workout?: Workout
}>()

// The owner changes the sentence, not just a word ("din"/"sin" bind to the
// noun in Swedish), so each ownership case is a complete message.
const messageKey = computed(() => {
  if (authStore.userId === props.workout?.user?.id) {
    return 'notifications.commentedOnYourWorkout'
  }

  if (props.actor?.id === props.workout?.user?.id) {
    return 'notifications.commentedOnTheirWorkout'
  }

  return 'notifications.commentedOnUsersWorkout'
})
</script>

<template>
  <RouterLink :to="`/workouts/${workout?.id}`" class="flex w-full items-center gap-x-3">
    <ChatBubbleLeftRightIcon class="size-7" />
    <div class="w-full font-normal">
      <i18n-t :keypath="messageKey" tag="div" scope="global">
        <template #name>
          <span class="font-semibold">{{ actor?.firstName }} {{ actor?.lastName }}</span>
        </template>
        <template #owner>{{ workout?.user?.firstName }}</template>
        <template #workout>
          <span class="font-semibold">{{ workout?.name }}</span>
        </template>
      </i18n-t>
      <p class="text-sm text-text-subtle">
        {{ formatUnixToRelativeDateTime(timestamp) }}
      </p>
    </div>
  </RouterLink>
</template>

<style scoped></style>
