// web/src/ui/profile/ProfileView.tsx
import type { User } from '@/proto/api/v1/shared_pb'
import type { ReactNode } from 'react'

import {
  ArrowRightOnRectangleIcon,
  BellIcon,
  ChartBarIcon,
  ChevronRightIcon,
  PencilSquareIcon,
  ShieldCheckIcon,
  UserCircleIcon,
} from '@heroicons/react/24/outline'
import { Code, ConnectError } from '@connectrpc/connect'
import { useEffect, useState } from 'react'
import { useTranslation } from 'react-i18next'
import { Link, useNavigate } from 'react-router-dom'

import {
  deleteAccount,
  getCurrentUser,
  updateUserAutofillSets,
  updateUserDistanceUnit,
  updateUserName,
  updateUserUsername,
  updateUserWeightUnit,
} from '@/http/requests'
import { DistanceUnit, WeightUnit } from '@/proto/api/v1/shared_pb'
import { clearAccountState } from '@/stores/accountState'
import { useToastStore } from '@/stores/toasts'
import { useAuthStore } from '@/stores/auth'
import { useDashboardStore } from '@/stores/dashboard'
import { useNotificationStore } from '@/stores/notifications'
import { usePreferencesStore } from '@/stores/preferences'
import { cn } from '@/ui/cn'
import { AppSheet, SheetAction } from '@/ui/components/AppSheet'
import { AppSkeleton } from '@/ui/components/AppSkeleton'
import { normalizeDistanceUnit } from '@/utils/distanceUnits'
import { handle, initials } from '@/utils/names'
import { formatNumber } from '@/utils/numbers'
import { normalizeWeightUnit } from '@/utils/weightUnits'
import styles from './ProfileView.module.css'

// Past this the badge is wider than the icon it sits on.
const maxBadgeCount = 99

const usernamePattern = '[A-Za-z0-9._]+'
const minUsernameLength = 3
const maxUsernameLength = 30

/** The Me tab: who you are, how you are doing, and what you can change. */
export const ProfileView = () => {
  const { t } = useTranslation()
  const navigate = useNavigate()

  const unreadCount = useNotificationStore((state) => state.unreadCount)
  const dashboard = useDashboardStore((state) => state.dashboard)
  const weightUnit = usePreferencesStore((state) => state.weightUnit)
  const distanceUnit = usePreferencesStore((state) => state.distanceUnit)
  const autofillSets = usePreferencesStore((state) => state.autofillSets)

  const [user, setUser] = useState<User>()
  const [saving, setSaving] = useState<'weight' | 'distance' | 'autofill' | 'name' | 'username'>()
  const [nameDraft, setNameDraft] = useState<string>()
  const [usernameDraft, setUsernameDraft] = useState<string>()
  const [deletePassword, setDeletePassword] = useState<string>()
  const [deleteError, setDeleteError] = useState<string>()
  const [deleting, setDeleting] = useState(false)

  useEffect(() => {
    const load = async () => {
      // Deleting the account swaps the signed-in shell for the guest one, which
      // remounts this screen under it before the app has left /profile. There
      // is no longer a user to ask about, and asking for an empty id answers
      // with a validation error the person reads as a failed deletion.
      const { userId } = useAuthStore.getState()
      if (!userId) return

      const [response] = await Promise.all([
        getCurrentUser(userId),
        useDashboardStore.getState().load(),
        useNotificationStore.getState().refreshUnreadNotifications(),
      ])
      if (!response?.user) return

      setUser(response.user)
      const preferences = usePreferencesStore.getState()
      preferences.setWeightUnit(response.user.weightUnit)
      preferences.setDistanceUnit(response.user.distanceUnit)
      preferences.setAutofillSets(response.user.autofillSets)
    }
    void load()
  }, [])

  /**
   * Applies a preference straight away, then tells the server.
   *
   * The request helper stays silent for network-level failures (Unavailable,
   * Unknown, Canceled), which is exactly when this reverts — so the revert says
   * why, or the control appears to snap back on its own.
   */
  const savePreference = async <T,>(
    field: 'weight' | 'distance' | 'autofill',
    previous: T,
    next: T,
    apply: (value: T) => void,
    request: () => Promise<unknown>,
    messages: { updated: string; failed: string },
  ) => {
    if (previous === next) return

    apply(next)
    setSaving(field)
    const res = await request()
    setSaving(undefined)

    if (!res) {
      apply(previous)
      useToastStore.getState().error(messages.failed)
      return
    }

    useToastStore.getState().success(messages.updated)
  }

  const saveName = async () => {
    if (!user || nameDraft === undefined || saving === 'name') return

    setSaving('name')
    const res = await updateUserName(nameDraft)
    setSaving(undefined)

    // Failures surface through the request helper's toast, so the sheet stays
    // open for the draft to be corrected.
    if (!res) return

    setUser({ ...user, name: res.user?.name ?? nameDraft })
    setNameDraft(undefined)
    useToastStore.getState().success(t('profile.nameUpdated'))
  }

  const saveUsername = async () => {
    if (!user || usernameDraft === undefined || saving === 'username') return

    setSaving('username')
    const res = await updateUserUsername(usernameDraft)
    setSaving(undefined)

    // Failures — including a taken username — surface through the request
    // helper's toast, so the sheet stays open for the draft to be corrected.
    if (!res) return

    setUser({ ...user, username: res.user?.username ?? usernameDraft })
    setUsernameDraft(undefined)
    useToastStore.getState().success(t('profile.usernameUpdated'))
  }

  /**
   * Deletes the account, then leaves nothing of it on the device.
   *
   * A wrong password comes back as InvalidArgument and stays on the field:
   * the sheet is the only place the password was typed, so closing it to show
   * a toast would lose the correction.
   */
  const confirmDelete = async () => {
    if (deletePassword === undefined || deleting) return

    setDeleting(true)
    setDeleteError(undefined)
    try {
      await deleteAccount(deletePassword)
    } catch (error) {
      setDeleting(false)
      setDeleteError(
        error instanceof ConnectError && error.code === Code.InvalidArgument
          ? t('profile.deleteAccountWrongPassword')
          : t('profile.deleteAccountFailed'),
      )
      return
    }

    clearAccountState()
    setDeletePassword(undefined)
    setDeleting(false)
    useToastStore.getState().success(t('profile.accountDeleted'))
    void navigate('/login')
  }

  if (!user) return <AppSkeleton />

  const preference = <T,>(
    title: string,
    body: string,
    options: { value: T; label: string }[],
    current: T,
    busy: boolean,
    onPick: (value: T) => void,
  ): ReactNode => (
    <section className={styles.preferencesCard}>
      <div>
        <strong>{title}</strong>
        <small>{body}</small>
      </div>
      <div className="segmented" role="group" aria-label={title}>
        {options.map((option) => (
          <button
            key={option.label}
            type="button"
            aria-pressed={current === option.value}
            className={cn(current === option.value && 'is-selected')}
            disabled={busy}
            onClick={() => onPick(option.value)}
          >
            {option.label}
          </button>
        ))}
      </div>
    </section>
  )

  return (
    <div className={styles.profileStack}>
      {/* A tab root opens with its own large title. This one used to open
          straight onto a card, which left it the only tab without one. */}
      <header className={styles.pageIntro}>
        <h1>{t('profile.heading')}</h1>
      </header>

      <section className={styles.profileCard}>
        <div className={styles.avatar}>{initials(user.name)}</div>
        <div className="min-w-0">
          <p className={styles.eyebrow}>{t('profile.account')}</p>
          {/* The name keeps its own heading element, so the pencil beside it
              stays out of the heading's accessible name. */}
          <div className={styles.nameLine}>
            <h2>{user.name}</h2>
            <button
              type="button"
              aria-label={t('profile.editName')}
              onClick={() => setNameDraft(user.name)}
            >
              <PencilSquareIcon aria-hidden="true" />
            </button>
          </div>
          <p className={styles.usernameLine}>
            <span className="truncate">{handle(user.username)}</span>
            <button
              type="button"
              aria-label={t('profile.editUsername')}
              onClick={() => setUsernameDraft(user.username)}
            >
              <PencilSquareIcon aria-hidden="true" />
            </button>
          </p>
          <p>{user.email}</p>
        </div>
        <Link
          to="/notifications"
          className={styles.notificationLink}
          aria-label={t('profile.notifications')}
        >
          <BellIcon aria-hidden="true" />
          {unreadCount > 0 && (
            <span className={styles.notificationBadge}>
              {unreadCount > maxBadgeCount ? `${maxBadgeCount}+` : unreadCount}
            </span>
          )}
        </Link>
      </section>

      <section className={styles.statsStrip} aria-label={t('profile.trainingSummary')}>
        <article>
          <strong>{dashboard?.recentWorkouts.length ?? 0}</strong>
          <small>{t('profile.workouts')}</small>
        </article>
        <article>
          <strong>{dashboard?.personalBests.length ?? 0}</strong>
          <small>{t('profile.records')}</small>
        </article>
        <article>
          <strong>
            {formatNumber(dashboard?.volumeThisWeek ?? 0)} {t('common.kg')}
          </strong>
          <small>{t('profile.thisWeek')}</small>
        </article>
      </section>

      <section className={styles.settingsCard}>
        <Link to="/progress">
          <span className={styles.settingsIcon}>
            <ChartBarIcon aria-hidden="true" />
          </span>
          <span>
            <strong>{t('profile.progress')}</strong>
            <small>{t('profile.progressBody')}</small>
          </span>
          <ChevronRightIcon aria-hidden="true" />
        </Link>
        <Link to={`/users/${user.id}`}>
          <span className={styles.settingsIcon}>
            <UserCircleIcon aria-hidden="true" />
          </span>
          <span>
            <strong>{t('profile.publicProfile')}</strong>
            <small>{t('profile.publicProfileBody')}</small>
          </span>
          <ChevronRightIcon aria-hidden="true" />
        </Link>
        <Link to="/privacy">
          <span className={styles.settingsIcon}>
            <ShieldCheckIcon aria-hidden="true" />
          </span>
          <span>
            <strong>{t('profile.privacyPolicy')}</strong>
            <small>{t('profile.privacyPolicyBody')}</small>
          </span>
          <ChevronRightIcon aria-hidden="true" />
        </Link>
      </section>

      {preference(
        t('profile.weightUnit'),
        t('profile.weightUnitBody'),
        [
          { value: WeightUnit.KILOGRAMS, label: t('auth.kilograms') },
          { value: WeightUnit.POUNDS, label: t('auth.pounds') },
        ],
        normalizeWeightUnit(weightUnit),
        saving === 'weight',
        (unit) =>
          void savePreference(
            'weight',
            normalizeWeightUnit(weightUnit),
            unit,
            usePreferencesStore.getState().setWeightUnit,
            () => updateUserWeightUnit(unit),
            {
              updated: t('profile.weightUnitUpdated'),
              failed: t('profile.weightUnitUpdateFailed'),
            },
          ),
      )}

      {preference(
        t('profile.distanceUnit'),
        t('profile.distanceUnitBody'),
        [
          { value: DistanceUnit.KILOMETERS, label: t('auth.kilometers') },
          { value: DistanceUnit.MILES, label: t('auth.miles') },
        ],
        normalizeDistanceUnit(distanceUnit),
        saving === 'distance',
        (unit) =>
          void savePreference(
            'distance',
            normalizeDistanceUnit(distanceUnit),
            unit,
            usePreferencesStore.getState().setDistanceUnit,
            () => updateUserDistanceUnit(unit),
            {
              updated: t('profile.distanceUnitUpdated'),
              failed: t('profile.distanceUnitUpdateFailed'),
            },
          ),
      )}

      {preference(
        t('profile.autofillSets'),
        t('profile.autofillSetsBody'),
        [
          { value: false, label: t('profile.autofillSetsOff') },
          { value: true, label: t('profile.autofillSetsOn') },
        ],
        autofillSets,
        saving === 'autofill',
        (enabled) =>
          void savePreference(
            'autofill',
            autofillSets,
            enabled,
            usePreferencesStore.getState().setAutofillSets,
            () => updateUserAutofillSets(enabled),
            {
              updated: t('profile.autofillSetsUpdated'),
              failed: t('profile.autofillSetsUpdateFailed'),
            },
          ),
      )}

      <Link to="/logout" className={styles.logoutLink}>
        <ArrowRightOnRectangleIcon aria-hidden="true" /> {t('auth.logout')}
      </Link>

      {/* Both app stores require an account made in the app to be deletable
          from inside it, which is why this sits on the profile rather than
          behind a support email. */}
      <section className={styles.dangerZone} aria-label={t('profile.dangerZone')}>
        <div>
          <strong>{t('profile.deleteAccount')}</strong>
          <small>{t('profile.deleteAccountBody')}</small>
        </div>
        <button
          type="button"
          onClick={() => {
            setDeleteError(undefined)
            setDeletePassword('')
          }}
        >
          {t('profile.deleteAccount')}
        </button>
      </section>

      {nameDraft !== undefined && (
        <AppSheet
          title={t('profile.editName')}
          closeLabel={t('common.close')}
          onClose={() => setNameDraft(undefined)}
          actions={
            <SheetAction type="submit" form="name-form" tone="primary" disabled={saving === 'name'}>
              {t('common.save')}
            </SheetAction>
          }
        >
          <form
            id="name-form"
            onSubmit={(event) => {
              event.preventDefault()
              void saveName()
            }}
          >
            <label htmlFor="edit-name" className="auth-label">
              {t('auth.name')}
            </label>
            <input
              id="edit-name"
              name="name"
              type="text"
              autoComplete="name"
              className="auth-input mt-2"
              required
              value={nameDraft}
              onChange={(event) => setNameDraft(event.target.value)}
            />
          </form>
        </AppSheet>
      )}

      {deletePassword !== undefined && (
        <AppSheet
          title={t('profile.deleteAccountTitle')}
          body={t('profile.deleteAccountWarning')}
          eyebrow={t('profile.dangerZone')}
          eyebrowTone="danger"
          closeLabel={t('common.close')}
          onClose={() => setDeletePassword(undefined)}
          actions={
            <>
              <SheetAction
                type="submit"
                form="delete-account-form"
                tone="danger"
                disabled={deleting}
              >
                {deleting ? t('profile.deleteAccountDeleting') : t('profile.deleteAccountConfirm')}
              </SheetAction>
              <SheetAction tone="tertiary" onClick={() => setDeletePassword(undefined)}>
                {t('common.cancel')}
              </SheetAction>
            </>
          }
        >
          <form
            id="delete-account-form"
            onSubmit={(event) => {
              event.preventDefault()
              void confirmDelete()
            }}
          >
            <label htmlFor="delete-account-password" className="auth-label">
              {t('profile.deleteAccountPassword')}
            </label>
            <input
              id="delete-account-password"
              name="password"
              type="password"
              autoComplete="current-password"
              className="auth-input mt-2"
              required
              value={deletePassword}
              onChange={(event) => setDeletePassword(event.target.value)}
            />
            {deleteError !== undefined && (
              <p role="alert" className="mt-2 text-sm text-danger">
                {deleteError}
              </p>
            )}
          </form>
        </AppSheet>
      )}

      {usernameDraft !== undefined && (
        <AppSheet
          title={t('profile.editUsername')}
          closeLabel={t('common.close')}
          onClose={() => setUsernameDraft(undefined)}
          actions={
            <SheetAction
              type="submit"
              form="username-form"
              tone="primary"
              disabled={saving === 'username'}
            >
              {t('common.save')}
            </SheetAction>
          }
        >
          <form
            id="username-form"
            onSubmit={(event) => {
              event.preventDefault()
              void saveUsername()
            }}
          >
            <label htmlFor="edit-username" className="auth-label">
              {t('auth.username')}
            </label>
            <p className="mt-1 text-sm text-text-subtle">{t('auth.usernameHelp')}</p>
            <input
              id="edit-username"
              name="username"
              type="text"
              autoComplete="username"
              autoCapitalize="none"
              spellCheck={false}
              className="auth-input mt-2"
              minLength={minUsernameLength}
              maxLength={maxUsernameLength}
              pattern={usernamePattern}
              required
              value={usernameDraft}
              // Usernames are lower-case, so the field settles the case rather
              // than rejecting what was typed.
              onChange={(event) => setUsernameDraft(event.target.value.toLowerCase())}
            />
          </form>
        </AppSheet>
      )}
    </div>
  )
}

// web/src/ui/profile/ProfileView.vue
<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import {
  ArrowRightOnRectangleIcon,
  BellIcon,
  ChartBarIcon,
  ChevronRightIcon,
  PencilSquareIcon,
  UserCircleIcon,
} from '@heroicons/vue/24/outline'

import {
  getCurrentUser,
  updateUserAutofillSets,
  updateUserDistanceUnit,
  updateUserUsername,
  updateUserWeightUnit,
} from '@/http/requests'
import AppSheet from '@/ui/components/AppSheet.vue'
import AppSkeleton from '@/ui/components/AppSkeleton.vue'
import { useAlertStore } from '@/stores/alerts'
import { useAuthStore } from '@/stores/auth'
import { useDashboardStore } from '@/stores/dashboard'
import { useNotificationStore } from '@/stores/notifications'
import { usePreferencesStore } from '@/stores/preferences'
import { DistanceUnit, WeightUnit, type User } from '@/proto/api/v1/shared_pb'
import { normalizeWeightUnit } from '@/utils/weightUnits'
import { normalizeDistanceUnit } from '@/utils/distanceUnits'
import { formatNumber } from '@/utils/numbers'
import { initials } from '@/utils/names'
import { useI18n } from 'vue-i18n'

const { t } = useI18n()
const user = ref<User>()
const authStore = useAuthStore()
const dashboardStore = useDashboardStore()
const notificationStore = useNotificationStore()
const alertStore = useAlertStore()
const preferencesStore = usePreferencesStore()
const updatingWeightUnit = ref(false)
const updatingDistanceUnit = ref(false)
const updatingAutofillSets = ref(false)

onMounted(async () => {
  const [response] = await Promise.all([
    getCurrentUser(authStore.userId),
    dashboardStore.load(),
    notificationStore.refreshUnreadNotifications(),
  ])
  if (response) {
    user.value = response.user
    preferencesStore.setWeightUnit(response.user?.weightUnit)
    preferencesStore.setDistanceUnit(response.user?.distanceUnit)
    preferencesStore.setAutofillSets(response.user?.autofillSets)
  }
})

const weightUnit = computed(() => preferencesStore.weightUnit)

const setWeightUnit = async (unit: WeightUnit) => {
  const previous = preferencesStore.weightUnit
  if (normalizeWeightUnit(previous) === normalizeWeightUnit(unit)) return

  preferencesStore.setWeightUnit(unit)
  updatingWeightUnit.value = true
  const res = await updateUserWeightUnit(unit)
  updatingWeightUnit.value = false

  // The request helper stays silent for network-level failures (Unavailable,
  // Unknown, Canceled), which is exactly when this reverts. Say so explicitly,
  // or the button appears to snap back on its own.
  if (!res) {
    preferencesStore.setWeightUnit(previous)
    alertStore.setError(t('profile.weightUnitUpdateFailed'))
    return
  }

  if (user.value) user.value.weightUnit = normalizeWeightUnit(res.user?.weightUnit)
  alertStore.setSuccess(t('profile.weightUnitUpdated'))
}

const distanceUnit = computed(() => preferencesStore.distanceUnit)

const setDistanceUnit = async (unit: DistanceUnit) => {
  const previous = preferencesStore.distanceUnit
  if (normalizeDistanceUnit(previous) === normalizeDistanceUnit(unit)) return

  preferencesStore.setDistanceUnit(unit)
  updatingDistanceUnit.value = true
  const res = await updateUserDistanceUnit(unit)
  updatingDistanceUnit.value = false

  // Same contract as the weight unit above: network-level failures resolve to
  // nothing, so the revert has to explain itself.
  if (!res) {
    preferencesStore.setDistanceUnit(previous)
    alertStore.setError(t('profile.distanceUnitUpdateFailed'))
    return
  }

  if (user.value) user.value.distanceUnit = normalizeDistanceUnit(res.user?.distanceUnit)
  alertStore.setSuccess(t('profile.distanceUnitUpdated'))
}

const autofillSets = computed(() => preferencesStore.autofillSets)

const setAutofillSets = async (enabled: boolean) => {
  const previous = preferencesStore.autofillSets
  if (previous === enabled) return

  preferencesStore.setAutofillSets(enabled)
  updatingAutofillSets.value = true
  const res = await updateUserAutofillSets(enabled)
  updatingAutofillSets.value = false

  // Same contract as the units above: a network failure resolves to nothing,
  // so the revert has to explain itself.
  if (!res) {
    preferencesStore.setAutofillSets(previous)
    alertStore.setError(t('profile.autofillSetsUpdateFailed'))
    return
  }

  if (user.value) user.value.autofillSets = res.user?.autofillSets ?? enabled
  alertStore.setSuccess(t('profile.autofillSetsUpdated'))
}

const userInitials = computed(() => initials(user.value?.name))

const editingUsername = ref(false)
const usernameDraft = ref('')
const savingUsername = ref(false)

const openUsernameEditor = () => {
  usernameDraft.value = user.value?.username ?? ''
  editingUsername.value = true
}

const saveUsername = async () => {
  if (!user.value || savingUsername.value) return

  savingUsername.value = true
  const res = await updateUserUsername(usernameDraft.value)
  savingUsername.value = false

  // Failures — including a taken username — surface through the request
  // helper's alert, so the sheet stays open for the draft to be corrected.
  if (!res) return

  user.value.username = res.user?.username ?? usernameDraft.value
  editingUsername.value = false
  alertStore.setSuccess(t('profile.usernameUpdated'))
}
const recentWorkoutCount = computed(() => dashboardStore.dashboard?.recentWorkouts.length ?? 0)
const weeklyVolume = computed(() => formatNumber(dashboardStore.dashboard?.volumeThisWeek ?? 0))
</script>

<template>
  <AppSkeleton v-if="!user" />
  <div v-else class="profile-stack">
    <!-- A tab root opens with its own large title. This one used to open
         straight onto a card, which left it the only tab without one. -->
    <header class="page-intro">
      <h1>{{ $t('profile.heading') }}</h1>
    </header>

    <section class="profile-card">
      <div class="avatar">{{ userInitials }}</div>
      <div class="min-w-0">
        <p class="eyebrow">{{ $t('profile.account') }}</p>
        <h2>{{ user.name }}</h2>
        <p class="username-line">
          <span class="truncate">@{{ user.username }}</span>
          <button
            type="button"
            :aria-label="$t('profile.editUsername')"
            @click="openUsernameEditor"
          >
            <PencilSquareIcon />
          </button>
        </p>
        <p>{{ user.email }}</p>
      </div>
      <RouterLink
        to="/notifications"
        class="notification-link"
        :aria-label="$t('profile.notifications')"
      >
        <BellIcon />
        <span v-if="notificationStore.unreadCount" class="notification-badge">
          {{ notificationStore.unreadCount > 99 ? '99+' : notificationStore.unreadCount }}
        </span>
      </RouterLink>
    </section>

    <section class="stats-strip" :aria-label="$t('profile.trainingSummary')">
      <article>
        <strong>{{ recentWorkoutCount }}</strong
        ><small>{{ $t('profile.workouts') }}</small>
      </article>
      <article>
        <strong>{{ dashboardStore.dashboard?.personalBests.length ?? 0 }}</strong
        ><small>{{ $t('profile.records') }}</small>
      </article>
      <article>
        <strong>{{ weeklyVolume }} {{ $t('common.kg') }}</strong
        ><small>{{ $t('profile.thisWeek') }}</small>
      </article>
    </section>

    <section class="settings-card">
      <RouterLink to="/progress"
        ><span class="settings-icon"><ChartBarIcon /></span
        ><span
          ><strong>{{ $t('profile.progress') }}</strong
          ><small>{{ $t('profile.progressBody') }}</small></span
        ><ChevronRightIcon
      /></RouterLink>
      <RouterLink :to="`/users/${user.id}`"
        ><span class="settings-icon"><UserCircleIcon /></span
        ><span
          ><strong>{{ $t('profile.publicProfile') }}</strong
          ><small>{{ $t('profile.publicProfileBody') }}</small></span
        ><ChevronRightIcon
      /></RouterLink>
    </section>

    <section class="preferences-card">
      <div>
        <strong>{{ $t('profile.weightUnit') }}</strong>
        <small>{{ $t('profile.weightUnitBody') }}</small>
      </div>
      <div class="segmented" role="group" :aria-label="$t('profile.weightUnit')">
        <button
          type="button"
          :aria-pressed="weightUnit === WeightUnit.KILOGRAMS"
          :class="{ 'is-selected': weightUnit === WeightUnit.KILOGRAMS }"
          :disabled="updatingWeightUnit"
          @click="setWeightUnit(WeightUnit.KILOGRAMS)"
        >
          {{ $t('auth.kilograms') }}
        </button>
        <button
          type="button"
          :aria-pressed="weightUnit === WeightUnit.POUNDS"
          :class="{ 'is-selected': weightUnit === WeightUnit.POUNDS }"
          :disabled="updatingWeightUnit"
          @click="setWeightUnit(WeightUnit.POUNDS)"
        >
          {{ $t('auth.pounds') }}
        </button>
      </div>
    </section>

    <section class="preferences-card">
      <div>
        <strong>{{ $t('profile.distanceUnit') }}</strong>
        <small>{{ $t('profile.distanceUnitBody') }}</small>
      </div>
      <div class="segmented" role="group" :aria-label="$t('profile.distanceUnit')">
        <button
          type="button"
          :aria-pressed="distanceUnit === DistanceUnit.KILOMETERS"
          :class="{ 'is-selected': distanceUnit === DistanceUnit.KILOMETERS }"
          :disabled="updatingDistanceUnit"
          @click="setDistanceUnit(DistanceUnit.KILOMETERS)"
        >
          {{ $t('auth.kilometers') }}
        </button>
        <button
          type="button"
          :aria-pressed="distanceUnit === DistanceUnit.MILES"
          :class="{ 'is-selected': distanceUnit === DistanceUnit.MILES }"
          :disabled="updatingDistanceUnit"
          @click="setDistanceUnit(DistanceUnit.MILES)"
        >
          {{ $t('auth.miles') }}
        </button>
      </div>
    </section>

    <section class="preferences-card">
      <div>
        <strong>{{ $t('profile.autofillSets') }}</strong>
        <small>{{ $t('profile.autofillSetsBody') }}</small>
      </div>
      <div class="segmented" role="group" :aria-label="$t('profile.autofillSets')">
        <button
          type="button"
          :aria-pressed="!autofillSets"
          :class="{ 'is-selected': !autofillSets }"
          :disabled="updatingAutofillSets"
          @click="setAutofillSets(false)"
        >
          {{ $t('profile.autofillSetsOff') }}
        </button>
        <button
          type="button"
          :aria-pressed="autofillSets"
          :class="{ 'is-selected': autofillSets }"
          :disabled="updatingAutofillSets"
          @click="setAutofillSets(true)"
        >
          {{ $t('profile.autofillSetsOn') }}
        </button>
      </div>
    </section>

    <RouterLink to="/logout" class="logout-link"
      ><ArrowRightOnRectangleIcon /> {{ $t('auth.logout') }}</RouterLink
    >

    <AppSheet
      v-if="editingUsername"
      :title="$t('profile.editUsername')"
      :close-label="$t('common.close')"
      @close="editingUsername = false"
    >
      <form id="username-form" @submit.prevent="saveUsername">
        <label for="edit-username" class="auth-label">{{ $t('auth.username') }}</label>
        <p class="mt-1 text-sm text-text-subtle">{{ $t('auth.usernameHelp') }}</p>
        <input
          id="edit-username"
          v-model="usernameDraft"
          name="username"
          type="text"
          autocomplete="username"
          autocapitalize="none"
          spellcheck="false"
          class="auth-input mt-2"
          minlength="3"
          maxlength="30"
          pattern="[A-Za-z0-9._]+"
          required
          @input="usernameDraft = usernameDraft.toLowerCase()"
        />
      </form>
      <template #actions>
        <button type="submit" form="username-form" class="primary" :disabled="savingUsername">
          {{ $t('common.save') }}
        </button>
      </template>
    </AppSheet>
  </div>
</template>

<style scoped>
@reference '../../assets/base.css';

.profile-stack {
  @apply mx-auto max-w-3xl space-y-5;
}
.profile-card {
  @apply card grid grid-cols-[auto_1fr_auto] items-center gap-4 p-5;
}
.avatar {
  @apply grid size-16 place-items-center rounded-card bg-ink text-xl font-semibold text-white;
}
.eyebrow {
  @apply text-eyebrow font-bold uppercase text-text-subtle;
}
.page-intro h1 {
  @apply px-1 text-display font-bold text-text;
}
.profile-card h2 {
  @apply mt-1 truncate text-title font-semibold text-text;
}
.profile-card p:last-child {
  @apply mt-1 truncate text-sm text-text-subtle;
}
/* The pencil is a full-size tap target, so the row's text centers against it
   with negative margins instead of growing the card. */
.username-line {
  @apply -my-2 flex items-center gap-0.5 text-sm text-text-muted;
}
.username-line button {
  @apply grid size-11 shrink-0 place-items-center rounded-control text-text-subtle transition hover:bg-ink-tint hover:text-text;
}
.username-line button svg {
  @apply size-4;
}
.notification-link {
  @apply relative grid size-14 place-items-center rounded-control text-text-muted transition hover:bg-ink-tint hover:text-text;
}
.notification-link > svg {
  @apply size-8;
}
.notification-badge {
  @apply absolute right-1 top-1 grid min-h-[22px] min-w-[22px] place-items-center rounded-full bg-badge px-1 text-eyebrow font-bold tracking-normal leading-none text-white ring-[3px] ring-white;
}
.stats-strip {
  @apply card grid grid-cols-3 divide-x divide-border p-4;
}
.stats-strip article {
  @apply grid min-w-0 gap-1 px-3 first:pl-0 last:pr-0;
}
.stats-strip strong {
  @apply truncate text-base font-semibold tracking-tight text-text sm:text-lg;
}
.stats-strip small {
  @apply text-xs text-text-subtle;
}
.settings-card {
  @apply card divide-y divide-border overflow-hidden;
}
.settings-card a {
  @apply grid grid-cols-[auto_1fr_auto] items-center gap-3 p-4 transition hover:bg-ink-surface hover:text-ink-strong;
}
.settings-card > a > svg {
  @apply size-5 text-text-subtle;
}
.settings-icon {
  @apply grid size-11 place-items-center rounded-control bg-ink-tint text-ink-strong;
}
.settings-icon svg {
  @apply size-5;
}
.settings-card strong,
.settings-card small {
  @apply block;
}
.settings-card small {
  @apply mt-0.5 text-sm text-text-subtle;
}
/* Stacked on a phone. Squeezing a segmented control into what is left of a row
   hides its second option behind a scroll nobody can see. */
.preferences-card {
  @apply card flex flex-col gap-3 p-4 sm:flex-row sm:items-center sm:justify-between;
}
.preferences-card strong,
.preferences-card small {
  @apply block;
}
.preferences-card strong {
  @apply text-base font-semibold text-text;
}
.preferences-card small {
  @apply mt-0.5 text-sm text-text-subtle;
}
.logout-link {
  @apply inline-flex min-h-(--size-control) w-full items-center justify-center gap-2 rounded-control border border-danger/30 bg-white px-4 text-sm font-semibold text-danger hover:bg-danger-surface hover:text-danger-strong;
}
.logout-link svg {
  @apply size-5;
}
</style>
