// web/src/ui/auth/ResetPassword.vue
<script setup lang="ts">
import { ref } from 'vue'
import { useI18n } from 'vue-i18n'
import { useRoute, useRouter } from 'vue-router'
import { updatePassword } from '@/http/requests'
import AppButton from '@/ui/components/AppButton.vue'
import AuthPasswordInput from '@/ui/auth/AuthPasswordInput.vue'
import { type UpdatePasswordRequest } from '@/proto/api/v1/auth_service_pb'
import { useAlertStore } from '@/stores/alerts.ts'

const { t } = useI18n()
const route = useRoute()
const router = useRouter()
const alertStore = useAlertStore()

const req = ref<UpdatePasswordRequest>({
  $typeName: 'api.v1.UpdatePasswordRequest',
  password: '',
  passwordConfirmation: '',
  token: route.query.token as string,
})

const onSignup = async () => {
  const res = await updatePassword(req.value)
  if (!res) return
  alertStore.setSuccess(t('auth.recovery.resetDone'))
  await router.push('/login')
}
</script>

<template>
  <section class="auth-view">
    <header class="auth-intro">
      <p class="auth-eyebrow">{{ t('auth.recovery.secureEyebrow') }}</p>
      <h1>{{ t('auth.recovery.chooseTitle') }}</h1>
      <p>{{ t('auth.recovery.chooseIntro') }}</p>
    </header>

    <form class="auth-form" method="POST" @submit.prevent="onSignup">
      <div>
        <label for="password" class="auth-label">{{ t('auth.recovery.newPassword') }}</label>
        <div class="mt-2">
          <AuthPasswordInput
            id="password"
            v-model="req.password"
            name="password"
            autocomplete="new-password"
          />
        </div>
      </div>

      <div>
        <label for="passwordConfirmation" class="auth-label">{{ t('auth.recovery.confirmNewPassword') }}</label>
        <div class="mt-2">
          <AuthPasswordInput
            id="passwordConfirmation"
            v-model="req.passwordConfirmation"
            name="passwordConfirmation"
            autocomplete="new-password"
          />
        </div>
      </div>

      <AppButton type="submit" colour="primary" class="auth-submit">{{ t('auth.recovery.updatePassword') }}</AppButton>
    </form>
  </section>
</template>

// web/src/ui/auth/ResetPassword.tsx
import { create } from '@bufbuild/protobuf'
import { useState } from 'react'
import { useTranslation } from 'react-i18next'
import { useNavigate, useSearchParams } from 'react-router-dom'

import { updatePassword } from '@/http/requests'
import posthog from '@/posthog'
import { UpdatePasswordRequestSchema } from '@/proto/api/v1/auth_service_pb'
import { useToastStore } from '@/stores/toasts'
import { AuthPasswordInput } from '@/ui/auth/AuthPasswordInput'
import { AppButton } from '@/ui/components/AppButton'

export const ResetPassword = () => {
  const { t } = useTranslation()
  const navigate = useNavigate()
  const [params] = useSearchParams()

  const [password, setPassword] = useState('')
  const [passwordConfirmation, setPasswordConfirmation] = useState('')

  const onSubmit = async (event: React.FormEvent) => {
    event.preventDefault()

    const res = await updatePassword(
      create(UpdatePasswordRequestSchema, {
        password,
        passwordConfirmation,
        token: params.get('token') ?? '',
      }),
    )
    if (!res) return

    posthog.capture('password_reset_completed')
    useToastStore.getState().success(t('auth.recovery.resetDone'))
    void navigate('/login')
  }

  return (
    <section className="auth-view">
      <header className="auth-intro">
        <p className="auth-eyebrow">{t('auth.recovery.secureEyebrow')}</p>
        <h1>{t('auth.recovery.chooseTitle')}</h1>
        <p>{t('auth.recovery.chooseIntro')}</p>
      </header>

      <form className="auth-form" method="POST" onSubmit={(event) => void onSubmit(event)}>
        <div>
          <label htmlFor="password" className="auth-label">
            {t('auth.recovery.newPassword')}
          </label>
          <div className="mt-2">
            <AuthPasswordInput
              id="password"
              name="password"
              autoComplete="new-password"
              value={password}
              onChange={setPassword}
            />
          </div>
        </div>

        <div>
          <label htmlFor="passwordConfirmation" className="auth-label">
            {t('auth.recovery.confirmNewPassword')}
          </label>
          <div className="mt-2">
            <AuthPasswordInput
              id="passwordConfirmation"
              name="passwordConfirmation"
              autoComplete="new-password"
              value={passwordConfirmation}
              onChange={setPasswordConfirmation}
            />
          </div>
        </div>

        <AppButton type="submit" colour="primary" className="auth-submit">
          {t('auth.recovery.updatePassword')}
        </AppButton>
      </form>
    </section>
  )
}
