// web/src/ui/auth/VerifyEmailPending.tsx
import { ClockIcon } from '@heroicons/react/24/outline'
import { useEffect, useState } from 'react'
import { useTranslation } from 'react-i18next'
import { Link } from 'react-router-dom'

import { resendVerificationEmail } from '@/http/requests'
import { selectHasPendingEmail, useEmailVerificationStore } from '@/stores/emailVerification'
import { AppButton } from '@/ui/components/AppButton'
import { AppInput } from '@/ui/components/AppInput'
import { maskEmail } from '@/utils/maskEmail'
import styles from './auth.module.css'

type ResendStatus = 'failed' | 'idle' | 'sending' | 'sent'

const cooldownRemaining = (now: number, lastSentAt: number, retryAfterSeconds: number) => {
  if (!lastSentAt) return 0
  const elapsed = (now - lastSentAt) / 1000
  return Math.max(0, Math.ceil(retryAfterSeconds - elapsed))
}

/**
 * The holding screen for an account that has signed up but not verified yet.
 *
 * Its whole job is the resend: it says what is being waited on, and offers one
 * new link at a time behind the cooldown the server reports.
 */
export const VerifyEmailPending = () => {
  const { t } = useTranslation()

  const pendingEmail = useEmailVerificationStore((state) => state.pendingEmail)
  const lastSentAt = useEmailVerificationStore((state) => state.lastSentAt)
  const retryAfterSeconds = useEmailVerificationStore((state) => state.retryAfterSeconds)
  const hasPendingEmail = useEmailVerificationStore(selectHasPendingEmail)

  const [status, setStatus] = useState<ResendStatus>('idle')
  const [email, setEmail] = useState('')
  const [now, setNow] = useState(() => Date.now())

  const secondsRemaining = cooldownRemaining(now, lastSentAt, retryAfterSeconds)
  const cooling = secondsRemaining > 0

  // Only while there is something to count down. Outside a cooldown nothing on
  // this screen changes with the clock.
  useEffect(() => {
    if (!cooling) return
    const ticker = setInterval(() => setNow(Date.now()), 1000)
    return () => clearInterval(ticker)
  }, [cooling])

  // The address is only shown when it can be masked, so that an unusable or
  // unexpected value is never printed in full.
  const maskedEmail = maskEmail(pendingEmail)
  const destination = hasPendingEmail ? pendingEmail : email.trim()
  const canResend = !cooling && status !== 'sending' && destination !== ''

  const resendLabel = () => {
    if (status === 'sending') return t('auth.verification.resending')
    if (cooling) return t('auth.verification.cooldownButton', { seconds: secondsRemaining })
    return t('auth.verification.resend')
  }

  const onSubmit = async (event: React.FormEvent) => {
    event.preventDefault()
    if (!canResend) return

    const address = destination
    setStatus('sending')

    const res = await resendVerificationEmail(address)
    if (!res) {
      setStatus('failed')
      return
    }

    useEmailVerificationStore.getState().markSent(address, res.retryAfterSeconds)
    // The cooldown starts now, so the countdown must not read from a clock that
    // is up to a tick behind.
    setNow(Date.now())
    setEmail('')
    setStatus('sent')
  }

  return (
    <section className={styles.view}>
      <header className={styles.intro}>
        <p className={styles.eyebrow}>{t('auth.verification.eyebrow')}</p>
        <h1>{t('auth.verification.title')}</h1>
        {maskedEmail ? (
          <p className={styles.destination}>
            {t('auth.verification.sentTo', { email: maskedEmail })}
          </p>
        ) : (
          <p>{t('auth.verification.unknownDestination')}</p>
        )}
      </header>

      <div className={styles.pending}>
        <ClockIcon className={styles.pendingIcon} aria-hidden="true" />
        <div className={styles.pendingBody}>
          <p className={styles.pendingLabel}>{t('auth.verification.pendingLabel')}</p>
          <p>{t('auth.verification.instructions')}</p>
        </div>
      </div>

      <form className={styles.form} method="POST" onSubmit={(event) => void onSubmit(event)}>
        <p className={styles.hint}>{t('auth.verification.notReceived')}</p>

        {!hasPendingEmail && (
          <AppInput
            id="verification-email"
            name="email"
            type="email"
            label={t('auth.email')}
            autoComplete="email"
            inputMode="email"
            required
            value={email}
            onChange={(event) => setEmail(event.target.value)}
          />
        )}

        <AppButton
          type="submit"
          colour="primary"
          size="lg"
          className="mt-2"
          disabled={!canResend}
          aria-busy={status === 'sending'}
        >
          {resendLabel()}
        </AppButton>

        {/* The countdown itself is the button's label, so the live region only
            reports what changed. */}
        <p className={styles.status} role="status" aria-live="polite">
          {status === 'sending' && <span>{t('auth.verification.resending')}</span>}
          {status === 'sent' && <span>{t('auth.verification.resent')}</span>}
        </p>

        {status === 'failed' && (
          <p className={styles.error} role="alert">
            {t('auth.verification.resendFailed')}
          </p>
        )}
      </form>

      <p className={styles.footer}>
        {t('auth.verification.differentEmailHelp')}{' '}
        <Link to="/signup" className={styles.link}>
          {t('auth.verification.differentEmail')}
        </Link>
      </p>

      <p className={styles.footer}>
        <Link to="/login" className={styles.link}>
          {t('auth.verification.backToLogin')}
        </Link>
      </p>
    </section>
  )
}

// web/src/ui/auth/VerifyEmailPending.vue
<script setup lang="ts">
import { computed, onBeforeUnmount, onMounted, ref } from 'vue'
import { RouterLink } from 'vue-router'
import { useI18n } from 'vue-i18n'
import { ClockIcon } from '@heroicons/vue/24/outline'
import AppButton from '@/ui/components/AppButton.vue'
import { resendVerificationEmail } from '@/http/requests'
import { useEmailVerificationStore } from '@/stores/emailVerification'
import { maskEmail } from '@/utils/maskEmail'

const { t } = useI18n()
const emailVerificationStore = useEmailVerificationStore()

type ResendStatus = 'failed' | 'idle' | 'sending' | 'sent'

const status = ref<ResendStatus>('idle')
const email = ref('')
const now = ref(Date.now())
let ticker: ReturnType<typeof setInterval> | undefined

onMounted(() => {
  ticker = setInterval(() => {
    now.value = Date.now()
  }, 1000)
})

onBeforeUnmount(() => {
  if (ticker) clearInterval(ticker)
})

const maskedEmail = computed(() => maskEmail(emailVerificationStore.pendingEmail))
// The address is only shown when it can be masked, so that an unusable or
// unexpected value is never printed in full.
const knowsDestination = computed(() => maskedEmail.value !== '')

const secondsRemaining = computed(() => {
  if (!emailVerificationStore.lastSentAt) return 0
  const elapsed = (now.value - emailVerificationStore.lastSentAt) / 1000
  return Math.max(0, Math.ceil(emailVerificationStore.retryAfterSeconds - elapsed))
})

const cooling = computed(() => secondsRemaining.value > 0)

const destination = computed(() =>
  emailVerificationStore.hasPendingEmail ? emailVerificationStore.pendingEmail : email.value.trim(),
)

const canResend = computed(
  () => !cooling.value && status.value !== 'sending' && destination.value !== '',
)

const resendLabel = computed(() => {
  if (status.value === 'sending') return t('auth.verification.resending')
  if (cooling.value)
    return t('auth.verification.cooldownButton', { seconds: secondsRemaining.value })
  return t('auth.verification.resend')
})

const onResend = async () => {
  if (!canResend.value) return

  const address = destination.value
  status.value = 'sending'

  const res = await resendVerificationEmail(address)
  if (!res) {
    status.value = 'failed'
    return
  }

  emailVerificationStore.markSent(address, res.retryAfterSeconds)
  email.value = ''
  status.value = 'sent'
}
</script>

<template>
  <section class="auth-view">
    <header class="auth-intro">
      <p class="auth-eyebrow">{{ t('auth.verification.eyebrow') }}</p>
      <h1>{{ t('auth.verification.title') }}</h1>
      <p v-if="knowsDestination" class="verification-destination">
        {{ t('auth.verification.sentTo', { email: maskedEmail }) }}
      </p>
      <p v-else>{{ t('auth.verification.unknownDestination') }}</p>
    </header>

    <div class="verification-pending">
      <ClockIcon class="verification-pending-icon" aria-hidden="true" />
      <div class="verification-pending-body">
        <p class="verification-pending-label">{{ t('auth.verification.pendingLabel') }}</p>
        <p>{{ t('auth.verification.instructions') }}</p>
      </div>
    </div>

    <form class="auth-form" method="POST" @submit.prevent="onResend">
      <p class="verification-hint">{{ t('auth.verification.notReceived') }}</p>

      <div v-if="!emailVerificationStore.hasPendingEmail">
        <label for="verification-email" class="auth-label">{{ t('auth.email') }}</label>
        <div class="mt-2">
          <input
            id="verification-email"
            v-model="email"
            name="email"
            type="email"
            autocomplete="email"
            class="auth-input"
            inputmode="email"
            required
          />
        </div>
      </div>

      <AppButton
        type="submit"
        colour="primary"
        class="auth-submit"
        :disabled="!canResend"
        :aria-busy="status === 'sending'"
      >
        {{ resendLabel }}
      </AppButton>

      <!-- The countdown itself is the button's label, so the live region only
           reports what changed. -->
      <p class="verification-status" role="status" aria-live="polite">
        <span v-if="status === 'sending'">{{ t('auth.verification.resending') }}</span>
        <span v-else-if="status === 'sent'">{{ t('auth.verification.resent') }}</span>
      </p>

      <p v-if="status === 'failed'" class="verification-error" role="alert">
        {{ t('auth.verification.resendFailed') }}
      </p>
    </form>

    <p class="auth-footer">
      {{ t('auth.verification.differentEmailHelp') }}
      <RouterLink to="/signup" class="auth-link">{{
        t('auth.verification.differentEmail')
      }}</RouterLink>
    </p>

    <p class="auth-footer">
      <RouterLink to="/login" class="auth-link">{{
        t('auth.verification.backToLogin')
      }}</RouterLink>
    </p>
  </section>
</template>

<style scoped>
@reference '../../assets/base.css';

.verification-destination {
  @apply break-words;
}

.verification-pending {
  @apply mb-6 flex items-start gap-3 rounded-xl border border-amber-300 bg-amber-50 p-4 text-sm text-amber-900;
}

.verification-pending-icon {
  @apply mt-0.5 size-5 shrink-0;
}

.verification-pending-body {
  @apply min-w-0 space-y-1;
}

.verification-pending-label {
  @apply font-semibold;
}

.verification-hint {
  @apply text-sm text-slate-600;
}

.verification-status {
  @apply text-sm font-semibold text-slate-700;
}

.verification-error {
  @apply rounded-xl border border-red-200 bg-red-50 p-3 text-sm font-semibold text-red-700;
}
</style>
