// web/src/ui/workouts/DurationInput.vue
<script setup lang="ts">
import { ref, watch } from 'vue'
import { formatMeasurementDuration } from '@/utils/exerciseMeasurements'

const model = defineModel<number | undefined>()

// The text is state of its own rather than a computed over the model: deriving
// it would reformat the field on every keystroke and rewrite what the user is
// typing. The model tracks the text; the text only snaps to the canonical
// format when the field is left.
const text = ref(model.value === undefined ? '' : formatMeasurementDuration(model.value))
const focused = ref(false)

const parseDuration = (raw: string): number | undefined => {
  const value = raw.trim()
  if (!value) return undefined

  if (value.includes(':')) {
    const [minutes = '0', seconds = '0'] = value.split(':')
    const parsedMinutes = Number(minutes || 0)
    const parsedSeconds = Number(seconds || 0)
    if (
      !Number.isFinite(parsedMinutes) ||
      !Number.isFinite(parsedSeconds) ||
      parsedMinutes < 0 ||
      parsedSeconds < 0
    ) {
      return model.value
    }
    return Math.round(parsedMinutes * 60 + Math.min(parsedSeconds, 59))
  }

  // Bare digits fill in from the right like a stopwatch: "45" is 45 seconds,
  // "130" is 1:30. Treating them as raw seconds ("130" = 2:10) surprises
  // anyone who typed what they read on a timer.
  const digits = value.replace(/\D/g, '')
  if (!digits) return model.value
  const seconds = Number(digits.slice(-2))
  const minutes = Number(digits.slice(0, -2) || 0)
  return minutes * 60 + seconds
}

// External writes (restoring a draft, copying the previous session's value on
// focus) must reach the display, but never rewrite text mid-typing.
watch(model, (value) => {
  if (focused.value && text.value.trim()) return
  text.value = value === undefined ? '' : formatMeasurementDuration(value)
})

const onInput = (event: Event) => {
  text.value = (event.target as HTMLInputElement).value
  model.value = parseDuration(text.value)
}

const onFocus = () => {
  focused.value = true
}

const onBlur = () => {
  focused.value = false
  text.value = model.value === undefined ? '' : formatMeasurementDuration(model.value)
}
</script>

<template>
  <input
    :value="text"
    type="text"
    inputmode="numeric"
    placeholder="m:ss"
    @input="onInput"
    @focus="onFocus"
    @blur="onBlur"
  />
</template>

// web-next/src/ui/workouts/DurationInput.tsx
import type { ComponentProps } from 'react'

import { useState } from 'react'
import { useTranslation } from 'react-i18next'

import { formatMeasurementDuration } from '@/utils/exerciseMeasurements'
import { parseDuration } from '@/utils/parseDuration'

interface Props extends Omit<ComponentProps<'input'>, 'value' | 'onChange' | 'type'> {
  value: number | undefined
  onChange: (seconds: number | undefined) => void
}

const display = (seconds: number | undefined) =>
  seconds === undefined ? '' : formatMeasurementDuration(seconds)

/**
 * A duration field that reads "1:30" and "130" alike.
 *
 * The text is state of its own rather than derived from the value: deriving it
 * would reformat the field on every keystroke and rewrite what is being typed.
 * The value follows the text; the text only snaps to the canonical format when
 * the field is left.
 */
export const DurationInput = ({ value, onChange, ...rest }: Props) => {
  const { t } = useTranslation()

  const [text, setText] = useState(() => display(value))
  const [focused, setFocused] = useState(false)

  // An external write — restoring a draft, or copying the previous session's
  // value on focus — has to reach the display, but must never rewrite text
  // mid-typing. Adjusted during render rather than in an effect: an effect
  // would paint the stale text first.
  const [seen, setSeen] = useState(value)
  if (value !== seen) {
    setSeen(value)
    if (!focused || !text.trim()) setText(display(value))
  }

  return (
    <input
      {...rest}
      value={text}
      type="text"
      inputMode="numeric"
      placeholder={t('workout.durationPlaceholder')}
      onChange={(event) => {
        setText(event.target.value)
        onChange(parseDuration(event.target.value, value))
      }}
      onFocus={(event) => {
        setFocused(true)
        rest.onFocus?.(event)
      }}
      onBlur={(event) => {
        setFocused(false)
        setText(display(value))
        rest.onBlur?.(event)
      }}
    />
  )
}
