// web/src/ui/routines/EditRoutine.vue
<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { useI18n } from 'vue-i18n'
import { useRoute, useRouter } from 'vue-router'

import { getRoutine, updateRoutine } from '@/http/requests'
import { useAlertStore } from '@/stores/alerts'
import RoutineForm from '@/ui/routines/RoutineForm.vue'

const { t } = useI18n()
const route = useRoute()
const router = useRouter()
const alertStore = useAlertStore()
const name = ref('')
const exerciseIds = ref<string[]>([])
const loading = ref(true)
const saving = ref(false)

onMounted(async () => {
  const response = await getRoutine(route.params.id as string)
  if (response?.routine) {
    name.value = response.routine.name
    exerciseIds.value = response.routine.exercises.map((exercise) => exercise.id)
  }
  loading.value = false
})

const onSave = async (updatedName: string, updatedExerciseIds: string[]) => {
  saving.value = true
  try {
    const response = await updateRoutine(route.params.id as string, updatedName, updatedExerciseIds)
    if (!response) return

    alertStore.setSuccess(t('routine.form.updated'))
    await router.push(`/routines/${route.params.id}`)
  } finally {
    saving.value = false
  }
}
</script>

<template>
  <div v-if="loading" class="card shadow-none p-6 text-sm text-slate-500">
    {{ t('routine.loading') }}
  </div>
  <RoutineForm
    v-else
    :submit-label="t('training.planForm.saveChanges')"
    :initial-name="name"
    :initial-exercise-ids="exerciseIds"
    :saving="saving"
    @save="onSave"
  />
</template>

// web-next/src/ui/routines/EditRoutine.tsx
import { useEffect, useState } from 'react'
import { useTranslation } from 'react-i18next'
import { useNavigate, useParams } from 'react-router-dom'

import { getRoutine, updateRoutine } from '@/http/requests'
import { useAlertStore } from '@/stores/alerts'
import { AppSkeleton } from '@/ui/components/AppSkeleton'
import { RoutineForm } from '@/ui/routines/RoutineForm'

export const EditRoutine = () => {
  const { t } = useTranslation()
  const navigate = useNavigate()
  const { id = '' } = useParams()

  const [name, setName] = useState('')
  const [exerciseIds, setExerciseIds] = useState<string[]>([])
  const [loading, setLoading] = useState(true)
  const [saving, setSaving] = useState(false)

  useEffect(() => {
    const load = async () => {
      const response = await getRoutine(id)
      if (response?.routine) {
        setName(response.routine.name)
        setExerciseIds(response.routine.exercises.map((exercise) => exercise.id))
      }
      setLoading(false)
    }
    void load()
  }, [id])

  const onSave = async (updatedName: string, updatedExerciseIds: string[]) => {
    setSaving(true)
    try {
      const response = await updateRoutine(id, updatedName, updatedExerciseIds)
      if (!response) return

      useAlertStore.getState().setSuccess(t('routine.form.updated'))
      await navigate(`/routines/${id}`)
    } finally {
      setSaving(false)
    }
  }

  // The form reads its initial values once, so it is only mounted with them.
  if (loading) return <AppSkeleton />

  return (
    <RoutineForm
      submitLabel={t('training.planForm.saveChanges')}
      initialName={name}
      initialExerciseIds={exerciseIds}
      saving={saving}
      onSave={(updatedName, updatedIds) => void onSave(updatedName, updatedIds)}
    />
  )
}
