// web-next/src/ui/users/UserWorkouts.tsx
import type { Workout } from '@/proto/api/v1/workout_service_pb'

import { useCallback, useEffect, useState } from 'react'
import { useTranslation } from 'react-i18next'
import { useParams } from 'react-router-dom'

import { listWorkouts } from '@/http/requests'
import { AppList } from '@/ui/components/AppList'
import { AppListItem } from '@/ui/components/AppListItem'
import { AppSkeleton } from '@/ui/components/AppSkeleton'
import { CardWorkout } from '@/ui/components/CardWorkout'
import { useInfiniteScroll } from '@/utils/useInfiniteScroll'
import { usePagination } from '@/utils/usePagination'

/** This profile's finished workouts, newest first. */
export const UserWorkouts = () => {
  const { t } = useTranslation()
  const { id = '' } = useParams()
  const { hasMorePages, currentPageToken, setFromResponse } = usePagination()

  const [workouts, setWorkouts] = useState<Workout[]>([])
  const [loaded, setLoaded] = useState(false)
  const [fetching, setFetching] = useState(false)

  const fetchWorkouts = useCallback(async () => {
    setFetching(true)
    try {
      const res = await listWorkouts([id], currentPageToken())
      if (!res) return

      setWorkouts((current) => [...current, ...res.workouts])
      setFromResponse(res.pagination)
    } finally {
      setFetching(false)
    }
  }, [id, currentPageToken, setFromResponse])

  useEffect(() => {
    const load = async () => {
      await fetchWorkouts()
      setLoaded(true)
    }
    void load()
  }, [fetchWorkouts])

  const sentinel = useInfiniteScroll<HTMLDivElement>(
    () => void fetchWorkouts(),
    hasMorePages && !fetching,
  )

  if (!loaded) return <AppSkeleton />

  return (
    <>
      {workouts.map((workout) => (
        <CardWorkout key={workout.id} compact workout={workout} />
      ))}

      {hasMorePages && <div ref={sentinel} aria-hidden="true" />}

      {workouts.length === 0 && (
        <AppList>
          <AppListItem>{t('common.nothingHere')}</AppListItem>
        </AppList>
      )}
    </>
  )
}

// web/src/ui/users/UserWorkouts.vue
<script setup lang="ts">
import CardWorkout from '@/ui/components/CardWorkout.vue'
import { listWorkouts } from '@/http/requests.ts'
import { onMounted, ref } from 'vue'
import { useI18n } from 'vue-i18n'
import type { Workout } from '@/proto/api/v1/workout_service_pb.ts'
import usePagination from '@/utils/usePagination.ts'
import { vInfiniteScroll } from '@vueuse/components'
import { usePageTitleStore } from '@/stores/pageTitle.ts'
import AppList from '@/ui/components/AppList.vue'
import AppListItem from '@/ui/components/AppListItem.vue'
import AppSkeleton from '@/ui/components/AppSkeleton.vue'

const { t } = useI18n()
const props = defineProps<{
  id: string
  pageTitle: string
}>()

const workouts = ref([] as Workout[])
const isMounted = ref(false)
const pageTitleStore = usePageTitleStore()
const { hasMorePages, pageToken, resolvePageToken } = usePagination()

onMounted(async () => {
  await fetchWorkouts()
  pageTitleStore.setPageTitle(props.pageTitle)
  isMounted.value = true
})

const fetchWorkouts = async () => {
  const userIds = [props.id]
  const res = await listWorkouts(userIds, pageToken.value)
  if (!res) return

  workouts.value = [...workouts.value, ...res.workouts]
  pageToken.value = resolvePageToken(res.pagination)
}
</script>

<template>
  <AppSkeleton v-if="!isMounted" />
  <CardWorkout v-for="workout in workouts" :key="workout.id" compact :workout="workout" />
  <div v-if="hasMorePages" v-infinite-scroll="fetchWorkouts" />
  <AppList v-if="isMounted && workouts.length === 0">
    <AppListItem>{{ t('common.nothingHere') }}</AppListItem>
  </AppList>
</template>

<style scoped></style>
