// web/src/ui/users/UserPersonalBests.vue
<script setup lang="ts">
import AppList from '@/ui/components/AppList.vue'
import { onMounted, ref } from 'vue'
import { useI18n } from 'vue-i18n'
import type { ExerciseSet } from '@/proto/api/v1/shared_pb.ts'
import { getPersonalBests } from '@/http/requests.ts'
import { useRoute } from 'vue-router'
import { usePageTitleStore } from '@/stores/pageTitle.ts'
import AppListItemLink from '@/ui/components/AppListItemLink.vue'
import { formatToRelativeDateTime } from '@/utils/datetime.ts'
import AppListItem from '@/ui/components/AppListItem.vue'
import ExerciseTags from '@/ui/exercises/ExerciseTags.vue'
import { formatExerciseSet } from '@/utils/exerciseMeasurements'

const { t } = useI18n()
const props = defineProps<{
  id: string
  pageTitle: string
}>()

const route = useRoute()
const isMounted = ref(false)
const pageTitleStore = usePageTitleStore()
const personalBests = ref([] as ExerciseSet[])

onMounted(async () => {
  await fetchPersonalBests()
  pageTitleStore.setPageTitle(props.pageTitle)
  isMounted.value = true
})

const fetchPersonalBests = async () => {
  const res = await getPersonalBests(route.params.id as string)
  if (!res) return

  personalBests.value = res.personalBests
}
</script>

<template>
  <AppList v-if="isMounted">
    <AppListItem v-if="personalBests.length === 0">{{ t('common.nothingHere') }}</AppListItem>
    <AppListItemLink
      v-for="pb in personalBests"
      :key="pb.exercise?.id"
      :to="`/exercises/${pb.exercise?.id}`"
    >
      <div class="font-semibold">
        {{ pb.exercise?.name }}
        <ExerciseTags compact :tags="pb.exercise?.tags" />
        <p class="text-sm text-gray-700 mt-1 font-normal">
          {{ formatToRelativeDateTime(pb.set?.metadata?.createdAt) }}
        </p>
      </div>
      {{ pb.set ? formatExerciseSet(pb.set, pb.exercise) : '' }}
    </AppListItemLink>
  </AppList>
</template>

<style scoped></style>

// web/src/ui/users/UserPersonalBests.tsx
import type { ExerciseSet } from '@/proto/api/v1/shared_pb'

import { useEffect, useState } from 'react'
import { useTranslation } from 'react-i18next'
import { useParams } from 'react-router-dom'

import { getPersonalBests } from '@/http/requests'
import { AppList } from '@/ui/components/AppList'
import { AppListItem, AppListItemLink } from '@/ui/components/AppListItem'
import { AppSkeleton } from '@/ui/components/AppSkeleton'
import { ExerciseTags } from '@/ui/exercises/ExerciseTags'
import { formatToRelativeDateTime } from '@/utils/datetime'
import { formatExerciseSet } from '@/utils/exerciseMeasurements'

/** This profile's best set for every exercise they have logged. */
export const UserPersonalBests = () => {
  const { t } = useTranslation()
  const { id = '' } = useParams()

  const [personalBests, setPersonalBests] = useState<ExerciseSet[]>([])
  const [loaded, setLoaded] = useState(false)

  useEffect(() => {
    const load = async () => {
      const res = await getPersonalBests(id)
      if (res) setPersonalBests(res.personalBests)
      setLoaded(true)
    }
    void load()
  }, [id])

  if (!loaded) return <AppSkeleton />

  return (
    <AppList>
      {personalBests.length === 0 && <AppListItem>{t('common.nothingHere')}</AppListItem>}
      {personalBests.map((best) => (
        <AppListItemLink key={best.exercise?.id} to={`/exercises/${best.exercise?.id}`}>
          <div className="font-semibold">
            {best.exercise?.name}
            <ExerciseTags compact tags={best.exercise?.tags} />
            <p className="mt-1 text-sm font-normal text-text-muted">
              {formatToRelativeDateTime(best.set?.metadata?.createdAt)}
            </p>
          </div>
          {best.set ? formatExerciseSet(best.set, best.exercise) : ''}
        </AppListItemLink>
      ))}
    </AppList>
  )
}
